version: "3.5"
services:
  isard-database:
    container_name: isard-database
    volumes:
      - "/opt/isard/database:/data"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - isard_network
    image: rethinkdb
    restart: unless-stopped
    logging:
        driver: none

  isard-nginx:
    container_name: isard-nginx
    volumes:
      - "/opt/isard/certs/default:/etc/nginx/external"
      - "/opt/isard/logs/nginx:/var/log/nginx"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - isard_network
    image: isard/nginx:1
    restart: unless-stopped
    depends_on:
      - isard-app

  isard-app:
    container_name: isard-app
    volumes:
      - "sshkeys:/root/.ssh"
      - "/opt/isard/certs:/certs"
      - "/opt/isard/logs:/isard/logs"
      - "/opt/isard/database/wizard:/isard/install/wizard"
      - "/opt/isard/backups:/isard/backups"
      - "/opt/isard/uploads:/isard/uploads"
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "isard-engine:127.0.0.1"
    networks:
      - isard_network
    image: isard/app:1
    restart: unless-stopped
    depends_on:
      - isard-database

volumes:
  sshkeys:

networks:
  isard_network:
    external: false
    name: isard_network
