// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: pkg/proto/hyper.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DesktopStartRequest_DesktopType int32

const (
	DesktopStartRequest_DESKTOP_TYPE_UNKNOWN DesktopStartRequest_DesktopType = 0
	DesktopStartRequest_DESKTOP_TYPE_KVM     DesktopStartRequest_DesktopType = 1 // TODO: Add the rest of the hypervisor drivers
)

// Enum value maps for DesktopStartRequest_DesktopType.
var (
	DesktopStartRequest_DesktopType_name = map[int32]string{
		0: "DESKTOP_TYPE_UNKNOWN",
		1: "DESKTOP_TYPE_KVM",
	}
	DesktopStartRequest_DesktopType_value = map[string]int32{
		"DESKTOP_TYPE_UNKNOWN": 0,
		"DESKTOP_TYPE_KVM":     1,
	}
)

func (x DesktopStartRequest_DesktopType) Enum() *DesktopStartRequest_DesktopType {
	p := new(DesktopStartRequest_DesktopType)
	*p = x
	return p
}

func (x DesktopStartRequest_DesktopType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesktopStartRequest_DesktopType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_hyper_proto_enumTypes[0].Descriptor()
}

func (DesktopStartRequest_DesktopType) Type() protoreflect.EnumType {
	return &file_pkg_proto_hyper_proto_enumTypes[0]
}

func (x DesktopStartRequest_DesktopType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesktopStartRequest_DesktopType.Descriptor instead.
func (DesktopStartRequest_DesktopType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 0}
}

type DesktopStartRequest_DesktopOS_DesktopOSType_Arch int32

const (
	DesktopStartRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_ARCH_UNKNOWN DesktopStartRequest_DesktopOS_DesktopOSType_Arch = 0
	DesktopStartRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_ARCH_X86_64  DesktopStartRequest_DesktopOS_DesktopOSType_Arch = 1
)

// Enum value maps for DesktopStartRequest_DesktopOS_DesktopOSType_Arch.
var (
	DesktopStartRequest_DesktopOS_DesktopOSType_Arch_name = map[int32]string{
		0: "DESKTOP_OS_TYPE_ARCH_UNKNOWN",
		1: "DESKTOP_OS_TYPE_ARCH_X86_64",
	}
	DesktopStartRequest_DesktopOS_DesktopOSType_Arch_value = map[string]int32{
		"DESKTOP_OS_TYPE_ARCH_UNKNOWN": 0,
		"DESKTOP_OS_TYPE_ARCH_X86_64":  1,
	}
)

func (x DesktopStartRequest_DesktopOS_DesktopOSType_Arch) Enum() *DesktopStartRequest_DesktopOS_DesktopOSType_Arch {
	p := new(DesktopStartRequest_DesktopOS_DesktopOSType_Arch)
	*p = x
	return p
}

func (x DesktopStartRequest_DesktopOS_DesktopOSType_Arch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesktopStartRequest_DesktopOS_DesktopOSType_Arch) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_hyper_proto_enumTypes[1].Descriptor()
}

func (DesktopStartRequest_DesktopOS_DesktopOSType_Arch) Type() protoreflect.EnumType {
	return &file_pkg_proto_hyper_proto_enumTypes[1]
}

func (x DesktopStartRequest_DesktopOS_DesktopOSType_Arch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesktopStartRequest_DesktopOS_DesktopOSType_Arch.Descriptor instead.
func (DesktopStartRequest_DesktopOS_DesktopOSType_Arch) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type DesktopStartRequest_DesktopOS_DesktopOSType_Machine int32

const (
	DesktopStartRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_MACHINE_UNKNOWN      DesktopStartRequest_DesktopOS_DesktopOSType_Machine = 0
	DesktopStartRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_MACHINE_PC_i44FX_4_2 DesktopStartRequest_DesktopOS_DesktopOSType_Machine = 1
)

// Enum value maps for DesktopStartRequest_DesktopOS_DesktopOSType_Machine.
var (
	DesktopStartRequest_DesktopOS_DesktopOSType_Machine_name = map[int32]string{
		0: "DESKTOP_OS_TYPE_MACHINE_UNKNOWN",
		1: "DESKTOP_OS_TYPE_MACHINE_PC_i44FX_4_2",
	}
	DesktopStartRequest_DesktopOS_DesktopOSType_Machine_value = map[string]int32{
		"DESKTOP_OS_TYPE_MACHINE_UNKNOWN":      0,
		"DESKTOP_OS_TYPE_MACHINE_PC_i44FX_4_2": 1,
	}
)

func (x DesktopStartRequest_DesktopOS_DesktopOSType_Machine) Enum() *DesktopStartRequest_DesktopOS_DesktopOSType_Machine {
	p := new(DesktopStartRequest_DesktopOS_DesktopOSType_Machine)
	*p = x
	return p
}

func (x DesktopStartRequest_DesktopOS_DesktopOSType_Machine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesktopStartRequest_DesktopOS_DesktopOSType_Machine) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_hyper_proto_enumTypes[2].Descriptor()
}

func (DesktopStartRequest_DesktopOS_DesktopOSType_Machine) Type() protoreflect.EnumType {
	return &file_pkg_proto_hyper_proto_enumTypes[2]
}

func (x DesktopStartRequest_DesktopOS_DesktopOSType_Machine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesktopStartRequest_DesktopOS_DesktopOSType_Machine.Descriptor instead.
func (DesktopStartRequest_DesktopOS_DesktopOSType_Machine) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

type DesktopStartRequest_DesktopOS_DesktopOSType_Type int32

const (
	DesktopStartRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_TYPE_UNKNOWN DesktopStartRequest_DesktopOS_DesktopOSType_Type = 0
	DesktopStartRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_TYPE_HVM     DesktopStartRequest_DesktopOS_DesktopOSType_Type = 1
)

// Enum value maps for DesktopStartRequest_DesktopOS_DesktopOSType_Type.
var (
	DesktopStartRequest_DesktopOS_DesktopOSType_Type_name = map[int32]string{
		0: "DESKTOP_OS_TYPE_TYPE_UNKNOWN",
		1: "DESKTOP_OS_TYPE_TYPE_HVM",
	}
	DesktopStartRequest_DesktopOS_DesktopOSType_Type_value = map[string]int32{
		"DESKTOP_OS_TYPE_TYPE_UNKNOWN": 0,
		"DESKTOP_OS_TYPE_TYPE_HVM":     1,
	}
)

func (x DesktopStartRequest_DesktopOS_DesktopOSType_Type) Enum() *DesktopStartRequest_DesktopOS_DesktopOSType_Type {
	p := new(DesktopStartRequest_DesktopOS_DesktopOSType_Type)
	*p = x
	return p
}

func (x DesktopStartRequest_DesktopOS_DesktopOSType_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesktopStartRequest_DesktopOS_DesktopOSType_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_hyper_proto_enumTypes[3].Descriptor()
}

func (DesktopStartRequest_DesktopOS_DesktopOSType_Type) Type() protoreflect.EnumType {
	return &file_pkg_proto_hyper_proto_enumTypes[3]
}

func (x DesktopStartRequest_DesktopOS_DesktopOSType_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesktopStartRequest_DesktopOS_DesktopOSType_Type.Descriptor instead.
func (DesktopStartRequest_DesktopOS_DesktopOSType_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 0, 0, 2}
}

type DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType int32

const (
	DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_TYPE_UNKNOWN  DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType = 0
	DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_TYPE_KEYBOARD DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType = 1
)

// Enum value maps for DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType.
var (
	DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType_name = map[int32]string{
		0: "DESKTOP_DEVICE_INPUT_TYPE_UNKNOWN",
		1: "DESKTOP_DEVICE_INPUT_TYPE_KEYBOARD",
	}
	DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType_value = map[string]int32{
		"DESKTOP_DEVICE_INPUT_TYPE_UNKNOWN":  0,
		"DESKTOP_DEVICE_INPUT_TYPE_KEYBOARD": 1,
	}
)

func (x DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) Enum() *DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType {
	p := new(DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType)
	*p = x
	return p
}

func (x DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_hyper_proto_enumTypes[4].Descriptor()
}

func (DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) Type() protoreflect.EnumType {
	return &file_pkg_proto_hyper_proto_enumTypes[4]
}

func (x DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType.Descriptor instead.
func (DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

type DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus int32

const (
	DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_BUS_UNKNOWN DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus = 0
	DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_BUS_PS2     DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus = 1
)

// Enum value maps for DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus.
var (
	DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus_name = map[int32]string{
		0: "DESKTOP_DEVICE_INPUT_BUS_UNKNOWN",
		1: "DESKTOP_DEVICE_INPUT_BUS_PS2",
	}
	DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus_value = map[string]int32{
		"DESKTOP_DEVICE_INPUT_BUS_UNKNOWN": 0,
		"DESKTOP_DEVICE_INPUT_BUS_PS2":     1,
	}
)

func (x DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) Enum() *DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus {
	p := new(DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus)
	*p = x
	return p
}

func (x DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_hyper_proto_enumTypes[5].Descriptor()
}

func (DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) Type() protoreflect.EnumType {
	return &file_pkg_proto_hyper_proto_enumTypes[5]
}

func (x DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus.Descriptor instead.
func (DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 1, 0, 1}
}

type DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType int32

const (
	DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DESKTOP_DEVICE_VIDEO_MODEL_TYPE_UNKNOWN DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType = 0
	DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DESKTOP_DEVICE_VIDEO_MODEL_TYPE_QXL     DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType = 1
)

// Enum value maps for DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType.
var (
	DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType_name = map[int32]string{
		0: "DESKTOP_DEVICE_VIDEO_MODEL_TYPE_UNKNOWN",
		1: "DESKTOP_DEVICE_VIDEO_MODEL_TYPE_QXL",
	}
	DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType_value = map[string]int32{
		"DESKTOP_DEVICE_VIDEO_MODEL_TYPE_UNKNOWN": 0,
		"DESKTOP_DEVICE_VIDEO_MODEL_TYPE_QXL":     1,
	}
)

func (x DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) Enum() *DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType {
	p := new(DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType)
	*p = x
	return p
}

func (x DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_hyper_proto_enumTypes[6].Descriptor()
}

func (DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) Type() protoreflect.EnumType {
	return &file_pkg_proto_hyper_proto_enumTypes[6]
}

func (x DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType.Descriptor instead.
func (DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 1, 2, 0, 0}
}

type DesktopStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    DesktopStartRequest_DesktopType     `protobuf:"varint,1,opt,name=type,proto3,enum=proto.DesktopStartRequest_DesktopType" json:"type,omitempty"`
	Name    string                              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Os      *DesktopStartRequest_DesktopOS      `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Devices *DesktopStartRequest_DesktopDevices `protobuf:"bytes,4,opt,name=devices,proto3" json:"devices,omitempty"`
	Memory  *DesktopStartRequest_DesktopMemory  `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Vcpu    *DesktopStartRequest_DesktopVCPU    `protobuf:"bytes,6,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
}

func (x *DesktopStartRequest) Reset() {
	*x = DesktopStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest) ProtoMessage() {}

func (x *DesktopStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0}
}

func (x *DesktopStartRequest) GetType() DesktopStartRequest_DesktopType {
	if x != nil {
		return x.Type
	}
	return DesktopStartRequest_DESKTOP_TYPE_UNKNOWN
}

func (x *DesktopStartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DesktopStartRequest) GetOs() *DesktopStartRequest_DesktopOS {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *DesktopStartRequest) GetDevices() *DesktopStartRequest_DesktopDevices {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *DesktopStartRequest) GetMemory() *DesktopStartRequest_DesktopMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *DesktopStartRequest) GetVcpu() *DesktopStartRequest_DesktopVCPU {
	if x != nil {
		return x.Vcpu
	}
	return nil
}

type DesktopStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pwd          string `protobuf:"bytes,1,opt,name=pwd,proto3" json:"pwd,omitempty"`
	SpicePort    int32  `protobuf:"varint,2,opt,name=spice_port,json=spicePort,proto3" json:"spice_port,omitempty"`
	SpiceTlsPort int32  `protobuf:"varint,3,opt,name=spice_tls_port,json=spiceTlsPort,proto3" json:"spice_tls_port,omitempty"`
	VncPort      int32  `protobuf:"varint,4,opt,name=vnc_port,json=vncPort,proto3" json:"vnc_port,omitempty"`
	VncTlsPort   int32  `protobuf:"varint,5,opt,name=vnc_tls_port,json=vncTlsPort,proto3" json:"vnc_tls_port,omitempty"`
}

func (x *DesktopStartResponse) Reset() {
	*x = DesktopStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartResponse) ProtoMessage() {}

func (x *DesktopStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartResponse.ProtoReflect.Descriptor instead.
func (*DesktopStartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{1}
}

func (x *DesktopStartResponse) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *DesktopStartResponse) GetSpicePort() int32 {
	if x != nil {
		return x.SpicePort
	}
	return 0
}

func (x *DesktopStartResponse) GetSpiceTlsPort() int32 {
	if x != nil {
		return x.SpiceTlsPort
	}
	return 0
}

func (x *DesktopStartResponse) GetVncPort() int32 {
	if x != nil {
		return x.VncPort
	}
	return 0
}

func (x *DesktopStartResponse) GetVncTlsPort() int32 {
	if x != nil {
		return x.VncTlsPort
	}
	return 0
}

type DesktopStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid   string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Delete bool   `protobuf:"varint,2,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *DesktopStopRequest) Reset() {
	*x = DesktopStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStopRequest) ProtoMessage() {}

func (x *DesktopStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStopRequest.ProtoReflect.Descriptor instead.
func (*DesktopStopRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{2}
}

func (x *DesktopStopRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DesktopStopRequest) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

type DesktopStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopStopResponse) Reset() {
	*x = DesktopStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStopResponse) ProtoMessage() {}

func (x *DesktopStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStopResponse.ProtoReflect.Descriptor instead.
func (*DesktopStopResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{3}
}

type DesktopStartRequest_DesktopOS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *DesktopStartRequest_DesktopOS_DesktopOSType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *DesktopStartRequest_DesktopOS) Reset() {
	*x = DesktopStartRequest_DesktopOS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest_DesktopOS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest_DesktopOS) ProtoMessage() {}

func (x *DesktopStartRequest_DesktopOS) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest_DesktopOS.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest_DesktopOS) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DesktopStartRequest_DesktopOS) GetType() *DesktopStartRequest_DesktopOS_DesktopOSType {
	if x != nil {
		return x.Type
	}
	return nil
}

type DesktopStartRequest_DesktopDevices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input   []*DesktopStartRequest_DesktopDevices_DesktopDeviceInput   `protobuf:"bytes,1,rep,name=input,proto3" json:"input,omitempty"`
	Graphic []*DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic `protobuf:"bytes,2,rep,name=graphic,proto3" json:"graphic,omitempty"`
	Video   []*DesktopStartRequest_DesktopDevices_DesktopDeviceVideo   `protobuf:"bytes,3,rep,name=video,proto3" json:"video,omitempty"`
}

func (x *DesktopStartRequest_DesktopDevices) Reset() {
	*x = DesktopStartRequest_DesktopDevices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest_DesktopDevices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest_DesktopDevices) ProtoMessage() {}

func (x *DesktopStartRequest_DesktopDevices) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest_DesktopDevices.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest_DesktopDevices) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DesktopStartRequest_DesktopDevices) GetInput() []*DesktopStartRequest_DesktopDevices_DesktopDeviceInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *DesktopStartRequest_DesktopDevices) GetGraphic() []*DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic {
	if x != nil {
		return x.Graphic
	}
	return nil
}

func (x *DesktopStartRequest_DesktopDevices) GetVideo() []*DesktopStartRequest_DesktopDevices_DesktopDeviceVideo {
	if x != nil {
		return x.Video
	}
	return nil
}

type DesktopStartRequest_DesktopMemory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Unit  string `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *DesktopStartRequest_DesktopMemory) Reset() {
	*x = DesktopStartRequest_DesktopMemory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest_DesktopMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest_DesktopMemory) ProtoMessage() {}

func (x *DesktopStartRequest_DesktopMemory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest_DesktopMemory.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest_DesktopMemory) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 2}
}

func (x *DesktopStartRequest_DesktopMemory) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DesktopStartRequest_DesktopMemory) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type DesktopStartRequest_DesktopVCPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num       int32  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Placement string `protobuf:"bytes,2,opt,name=placement,proto3" json:"placement,omitempty"`
}

func (x *DesktopStartRequest_DesktopVCPU) Reset() {
	*x = DesktopStartRequest_DesktopVCPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest_DesktopVCPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest_DesktopVCPU) ProtoMessage() {}

func (x *DesktopStartRequest_DesktopVCPU) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest_DesktopVCPU.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest_DesktopVCPU) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 3}
}

func (x *DesktopStartRequest_DesktopVCPU) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *DesktopStartRequest_DesktopVCPU) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

type DesktopStartRequest_DesktopOS_DesktopOSType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arch    DesktopStartRequest_DesktopOS_DesktopOSType_Arch    `protobuf:"varint,1,opt,name=arch,proto3,enum=proto.DesktopStartRequest_DesktopOS_DesktopOSType_Arch" json:"arch,omitempty"`
	Machine DesktopStartRequest_DesktopOS_DesktopOSType_Machine `protobuf:"varint,2,opt,name=machine,proto3,enum=proto.DesktopStartRequest_DesktopOS_DesktopOSType_Machine" json:"machine,omitempty"`
	Type    DesktopStartRequest_DesktopOS_DesktopOSType_Type    `protobuf:"varint,3,opt,name=type,proto3,enum=proto.DesktopStartRequest_DesktopOS_DesktopOSType_Type" json:"type,omitempty"`
}

func (x *DesktopStartRequest_DesktopOS_DesktopOSType) Reset() {
	*x = DesktopStartRequest_DesktopOS_DesktopOSType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest_DesktopOS_DesktopOSType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest_DesktopOS_DesktopOSType) ProtoMessage() {}

func (x *DesktopStartRequest_DesktopOS_DesktopOSType) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest_DesktopOS_DesktopOSType.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest_DesktopOS_DesktopOSType) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *DesktopStartRequest_DesktopOS_DesktopOSType) GetArch() DesktopStartRequest_DesktopOS_DesktopOSType_Arch {
	if x != nil {
		return x.Arch
	}
	return DesktopStartRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_ARCH_UNKNOWN
}

func (x *DesktopStartRequest_DesktopOS_DesktopOSType) GetMachine() DesktopStartRequest_DesktopOS_DesktopOSType_Machine {
	if x != nil {
		return x.Machine
	}
	return DesktopStartRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_MACHINE_UNKNOWN
}

func (x *DesktopStartRequest_DesktopOS_DesktopOSType) GetType() DesktopStartRequest_DesktopOS_DesktopOSType_Type {
	if x != nil {
		return x.Type
	}
	return DesktopStartRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_TYPE_UNKNOWN
}

type DesktopStartRequest_DesktopDevices_DesktopDeviceInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType" json:"type,omitempty"`
	Bus  DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus  `protobuf:"varint,2,opt,name=bus,proto3,enum=proto.DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus" json:"bus,omitempty"`
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceInput) Reset() {
	*x = DesktopStartRequest_DesktopDevices_DesktopDeviceInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest_DesktopDevices_DesktopDeviceInput) ProtoMessage() {}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest_DesktopDevices_DesktopDeviceInput.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest_DesktopDevices_DesktopDeviceInput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceInput) GetType() DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType {
	if x != nil {
		return x.Type
	}
	return DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_TYPE_UNKNOWN
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceInput) GetBus() DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus {
	if x != nil {
		return x.Bus
	}
	return DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_BUS_UNKNOWN
}

type DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spice bool `protobuf:"varint,1,opt,name=spice,proto3" json:"spice,omitempty"`
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic) Reset() {
	*x = DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic) ProtoMessage() {}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic) GetSpice() bool {
	if x != nil {
		return x.Spice
	}
	return false
}

type DesktopStartRequest_DesktopDevices_DesktopDeviceVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceVideo) Reset() {
	*x = DesktopStartRequest_DesktopDevices_DesktopDeviceVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest_DesktopDevices_DesktopDeviceVideo) ProtoMessage() {}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceVideo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest_DesktopDevices_DesktopDeviceVideo.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest_DesktopDevices_DesktopDeviceVideo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 1, 2}
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceVideo) GetModel() *DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType" json:"type,omitempty"`
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) Reset() {
	*x = DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) ProtoMessage() {
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0, 1, 2, 0}
}

func (x *DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) GetType() DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType {
	if x != nil {
		return x.Type
	}
	return DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DESKTOP_DEVICE_VIDEO_MODEL_TYPE_UNKNOWN
}

var File_pkg_proto_hyper_proto protoreflect.FileDescriptor

var file_pkg_proto_hyper_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x79, 0x70, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea,
	0x11, 0x0a, 0x13, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74,
	0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x43, 0x0a, 0x07,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x12, 0x40, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x12, 0x3a, 0x0a, 0x04, 0x76, 0x63, 0x70, 0x75, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x56, 0x43, 0x50, 0x55, 0x52, 0x04, 0x76, 0x63, 0x70, 0x75, 0x1a,
	0xc2, 0x04, 0x0a, 0x09, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x12, 0x46, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f,
	0x53, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0xec, 0x03, 0x0a, 0x0d, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4b, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x2e, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x52, 0x04,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x54, 0x0a, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x2e, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x4b, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x2e, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x49, 0x0a, 0x04, 0x41, 0x72, 0x63, 0x68, 0x12,
	0x20, 0x0a, 0x1c, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x4f, 0x53, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x4f, 0x53, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x58, 0x38, 0x36, 0x5f, 0x36, 0x34,
	0x10, 0x01, 0x22, 0x58, 0x0a, 0x07, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x23, 0x0a,
	0x1f, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x4f, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x28, 0x0a, 0x24, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x4f, 0x53,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x5f, 0x50, 0x43,
	0x5f, 0x69, 0x34, 0x34, 0x46, 0x58, 0x5f, 0x34, 0x5f, 0x32, 0x10, 0x01, 0x22, 0x46, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x1c, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f,
	0x4f, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f,
	0x50, 0x5f, 0x4f, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x48,
	0x56, 0x4d, 0x10, 0x01, 0x1a, 0x8b, 0x09, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x52, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x58, 0x0a, 0x07, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x69, 0x63, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x63, 0x52, 0x07, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x69, 0x63, 0x12, 0x52, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x1a, 0xad, 0x03, 0x0a, 0x12, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x67, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x53,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74,
	0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x64, 0x0a, 0x03, 0x62, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x52, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x42, 0x75, 0x73, 0x52, 0x03, 0x62, 0x75, 0x73, 0x22,
	0x67, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x21, 0x44, 0x45, 0x53,
	0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x49, 0x4e, 0x50, 0x55,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x26, 0x0a, 0x22, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49,
	0x43, 0x45, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4b, 0x45,
	0x59, 0x42, 0x4f, 0x41, 0x52, 0x44, 0x10, 0x01, 0x22, 0x5f, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x42, 0x75,
	0x73, 0x12, 0x24, 0x0a, 0x20, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56,
	0x49, 0x43, 0x45, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x5f, 0x42, 0x55, 0x53, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x44, 0x45, 0x53, 0x4b, 0x54,
	0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x5f,
	0x42, 0x55, 0x53, 0x5f, 0x50, 0x53, 0x32, 0x10, 0x01, 0x1a, 0x2c, 0x0a, 0x14, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69,
	0x63, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x73, 0x70, 0x69, 0x63, 0x65, 0x1a, 0x98, 0x03, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x6a,
	0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x54, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x95, 0x02, 0x0a, 0x17, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x84, 0x01, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x73, 0x0a,
	0x1b, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x27,
	0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x56,
	0x49, 0x44, 0x45, 0x4f, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x27, 0x0a, 0x23, 0x44, 0x45, 0x53,
	0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x56, 0x49, 0x44, 0x45,
	0x4f, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x51, 0x58, 0x4c,
	0x10, 0x01, 0x1a, 0x39, 0x0a, 0x0d, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x1a, 0x3d, 0x0a,
	0x0b, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x56, 0x43, 0x50, 0x55, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x0b,
	0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x44,
	0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4b, 0x56, 0x4d, 0x10, 0x01, 0x22, 0xaa, 0x01, 0x0a, 0x14,
	0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x70, 0x69, 0x63, 0x65, 0x5f,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x69, 0x63,
	0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x70, 0x69, 0x63, 0x65, 0x5f, 0x74,
	0x6c, 0x73, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73,
	0x70, 0x69, 0x63, 0x65, 0x54, 0x6c, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76,
	0x6e, 0x63, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76,
	0x6e, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x76, 0x6e, 0x63, 0x5f, 0x74, 0x6c,
	0x73, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x76, 0x6e,
	0x63, 0x54, 0x6c, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x40, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x9a, 0x01, 0x0a, 0x05, 0x48, 0x79, 0x70, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x0c, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x73, 0x61,
	0x72, 0x64, 0x2d, 0x76, 0x64, 0x69, 0x2f, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2f, 0x68, 0x79, 0x70,
	0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_hyper_proto_rawDescOnce sync.Once
	file_pkg_proto_hyper_proto_rawDescData = file_pkg_proto_hyper_proto_rawDesc
)

func file_pkg_proto_hyper_proto_rawDescGZIP() []byte {
	file_pkg_proto_hyper_proto_rawDescOnce.Do(func() {
		file_pkg_proto_hyper_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_hyper_proto_rawDescData)
	})
	return file_pkg_proto_hyper_proto_rawDescData
}

var file_pkg_proto_hyper_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_pkg_proto_hyper_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_proto_hyper_proto_goTypes = []interface{}{
	(DesktopStartRequest_DesktopType)(0),                                                                           // 0: proto.DesktopStartRequest.DesktopType
	(DesktopStartRequest_DesktopOS_DesktopOSType_Arch)(0),                                                          // 1: proto.DesktopStartRequest.DesktopOS.DesktopOSType.Arch
	(DesktopStartRequest_DesktopOS_DesktopOSType_Machine)(0),                                                       // 2: proto.DesktopStartRequest.DesktopOS.DesktopOSType.Machine
	(DesktopStartRequest_DesktopOS_DesktopOSType_Type)(0),                                                          // 3: proto.DesktopStartRequest.DesktopOS.DesktopOSType.Type
	(DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType)(0),                              // 4: proto.DesktopStartRequest.DesktopDevices.DesktopDeviceInput.DesktopDeviceInputType
	(DesktopStartRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus)(0),                               // 5: proto.DesktopStartRequest.DesktopDevices.DesktopDeviceInput.DesktopDeviceInputBus
	(DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType)(0), // 6: proto.DesktopStartRequest.DesktopDevices.DesktopDeviceVideo.DesktopDeviceVideoModel.DesktopDeviceVideoModelType
	(*DesktopStartRequest)(nil),                                                                                    // 7: proto.DesktopStartRequest
	(*DesktopStartResponse)(nil),                                                                                   // 8: proto.DesktopStartResponse
	(*DesktopStopRequest)(nil),                                                                                     // 9: proto.DesktopStopRequest
	(*DesktopStopResponse)(nil),                                                                                    // 10: proto.DesktopStopResponse
	(*DesktopStartRequest_DesktopOS)(nil),                                                                          // 11: proto.DesktopStartRequest.DesktopOS
	(*DesktopStartRequest_DesktopDevices)(nil),                                                                     // 12: proto.DesktopStartRequest.DesktopDevices
	(*DesktopStartRequest_DesktopMemory)(nil),                                                                      // 13: proto.DesktopStartRequest.DesktopMemory
	(*DesktopStartRequest_DesktopVCPU)(nil),                                                                        // 14: proto.DesktopStartRequest.DesktopVCPU
	(*DesktopStartRequest_DesktopOS_DesktopOSType)(nil),                                                            // 15: proto.DesktopStartRequest.DesktopOS.DesktopOSType
	(*DesktopStartRequest_DesktopDevices_DesktopDeviceInput)(nil),                                                  // 16: proto.DesktopStartRequest.DesktopDevices.DesktopDeviceInput
	(*DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic)(nil),                                                // 17: proto.DesktopStartRequest.DesktopDevices.DesktopDeviceGraphic
	(*DesktopStartRequest_DesktopDevices_DesktopDeviceVideo)(nil),                                                  // 18: proto.DesktopStartRequest.DesktopDevices.DesktopDeviceVideo
	(*DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel)(nil),                          // 19: proto.DesktopStartRequest.DesktopDevices.DesktopDeviceVideo.DesktopDeviceVideoModel
}
var file_pkg_proto_hyper_proto_depIdxs = []int32{
	0,  // 0: proto.DesktopStartRequest.type:type_name -> proto.DesktopStartRequest.DesktopType
	11, // 1: proto.DesktopStartRequest.os:type_name -> proto.DesktopStartRequest.DesktopOS
	12, // 2: proto.DesktopStartRequest.devices:type_name -> proto.DesktopStartRequest.DesktopDevices
	13, // 3: proto.DesktopStartRequest.memory:type_name -> proto.DesktopStartRequest.DesktopMemory
	14, // 4: proto.DesktopStartRequest.vcpu:type_name -> proto.DesktopStartRequest.DesktopVCPU
	15, // 5: proto.DesktopStartRequest.DesktopOS.type:type_name -> proto.DesktopStartRequest.DesktopOS.DesktopOSType
	16, // 6: proto.DesktopStartRequest.DesktopDevices.input:type_name -> proto.DesktopStartRequest.DesktopDevices.DesktopDeviceInput
	17, // 7: proto.DesktopStartRequest.DesktopDevices.graphic:type_name -> proto.DesktopStartRequest.DesktopDevices.DesktopDeviceGraphic
	18, // 8: proto.DesktopStartRequest.DesktopDevices.video:type_name -> proto.DesktopStartRequest.DesktopDevices.DesktopDeviceVideo
	1,  // 9: proto.DesktopStartRequest.DesktopOS.DesktopOSType.arch:type_name -> proto.DesktopStartRequest.DesktopOS.DesktopOSType.Arch
	2,  // 10: proto.DesktopStartRequest.DesktopOS.DesktopOSType.machine:type_name -> proto.DesktopStartRequest.DesktopOS.DesktopOSType.Machine
	3,  // 11: proto.DesktopStartRequest.DesktopOS.DesktopOSType.type:type_name -> proto.DesktopStartRequest.DesktopOS.DesktopOSType.Type
	4,  // 12: proto.DesktopStartRequest.DesktopDevices.DesktopDeviceInput.type:type_name -> proto.DesktopStartRequest.DesktopDevices.DesktopDeviceInput.DesktopDeviceInputType
	5,  // 13: proto.DesktopStartRequest.DesktopDevices.DesktopDeviceInput.bus:type_name -> proto.DesktopStartRequest.DesktopDevices.DesktopDeviceInput.DesktopDeviceInputBus
	19, // 14: proto.DesktopStartRequest.DesktopDevices.DesktopDeviceVideo.model:type_name -> proto.DesktopStartRequest.DesktopDevices.DesktopDeviceVideo.DesktopDeviceVideoModel
	6,  // 15: proto.DesktopStartRequest.DesktopDevices.DesktopDeviceVideo.DesktopDeviceVideoModel.type:type_name -> proto.DesktopStartRequest.DesktopDevices.DesktopDeviceVideo.DesktopDeviceVideoModel.DesktopDeviceVideoModelType
	7,  // 16: proto.Hyper.DesktopStart:input_type -> proto.DesktopStartRequest
	9,  // 17: proto.Hyper.DesktopStop:input_type -> proto.DesktopStopRequest
	8,  // 18: proto.Hyper.DesktopStart:output_type -> proto.DesktopStartResponse
	10, // 19: proto.Hyper.DesktopStop:output_type -> proto.DesktopStopResponse
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pkg_proto_hyper_proto_init() }
func file_pkg_proto_hyper_proto_init() {
	if File_pkg_proto_hyper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_hyper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest_DesktopOS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest_DesktopDevices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest_DesktopMemory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest_DesktopVCPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest_DesktopOS_DesktopOSType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest_DesktopDevices_DesktopDeviceInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest_DesktopDevices_DesktopDeviceGraphic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest_DesktopDevices_DesktopDeviceVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_hyper_proto_rawDesc,
			NumEnums:      7,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_hyper_proto_goTypes,
		DependencyIndexes: file_pkg_proto_hyper_proto_depIdxs,
		EnumInfos:         file_pkg_proto_hyper_proto_enumTypes,
		MessageInfos:      file_pkg_proto_hyper_proto_msgTypes,
	}.Build()
	File_pkg_proto_hyper_proto = out.File
	file_pkg_proto_hyper_proto_rawDesc = nil
	file_pkg_proto_hyper_proto_goTypes = nil
	file_pkg_proto_hyper_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HyperClient is the client API for Hyper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HyperClient interface {
	DesktopStart(ctx context.Context, in *DesktopStartRequest, opts ...grpc.CallOption) (*DesktopStartResponse, error)
	DesktopStop(ctx context.Context, in *DesktopStopRequest, opts ...grpc.CallOption) (*DesktopStopResponse, error)
}

type hyperClient struct {
	cc grpc.ClientConnInterface
}

func NewHyperClient(cc grpc.ClientConnInterface) HyperClient {
	return &hyperClient{cc}
}

func (c *hyperClient) DesktopStart(ctx context.Context, in *DesktopStartRequest, opts ...grpc.CallOption) (*DesktopStartResponse, error) {
	out := new(DesktopStartResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) DesktopStop(ctx context.Context, in *DesktopStopRequest, opts ...grpc.CallOption) (*DesktopStopResponse, error) {
	out := new(DesktopStopResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopStop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HyperServer is the server API for Hyper service.
type HyperServer interface {
	DesktopStart(context.Context, *DesktopStartRequest) (*DesktopStartResponse, error)
	DesktopStop(context.Context, *DesktopStopRequest) (*DesktopStopResponse, error)
}

// UnimplementedHyperServer can be embedded to have forward compatible implementations.
type UnimplementedHyperServer struct {
}

func (*UnimplementedHyperServer) DesktopStart(context.Context, *DesktopStartRequest) (*DesktopStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopStart not implemented")
}
func (*UnimplementedHyperServer) DesktopStop(context.Context, *DesktopStopRequest) (*DesktopStopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopStop not implemented")
}

func RegisterHyperServer(s *grpc.Server, srv HyperServer) {
	s.RegisterService(&_Hyper_serviceDesc, srv)
}

func _Hyper_DesktopStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopStart(ctx, req.(*DesktopStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_DesktopStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopStop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopStop(ctx, req.(*DesktopStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hyper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Hyper",
	HandlerType: (*HyperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DesktopStart",
			Handler:    _Hyper_DesktopStart_Handler,
		},
		{
			MethodName: "DesktopStop",
			Handler:    _Hyper_DesktopStop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/hyper.proto",
}
