version: "3.5"
services:
  isard-squid:
    container_name: isard-squid
    image: ${DOCKER_IMAGE_PREFIX}squid:${DOCKER_IMAGE_TAG-latest}
    networks:
      - isard-network
    restart: unless-stopped
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: docker/squid/Dockerfile
      target: production
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    env_file:
      - .env

networks:
  isard-network:
    external: false
    name: isard-network
