version: "3.5"
services:
  isard-api:
    container_name: isard-api
    image: isard/api:${TAG:-latest}
    ports:
      - "7039:7039"
    networks:
      - isard-network
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BUILD_ROOT_PATH}/webapp/webapp/lib:/api/lib:ro
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: api/docker/Dockerfile
      target: production
    env_file:
      - .env

networks:
  isard-network:
    external: false
    name: isard-network
