const { error } = require('console')
const animate = require('tailwindcss-animate')

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  safelist: ['dark'],
  prefix: '',
  
  content: [
    './pages/**/*.{ts,tsx,vue}',
    './components/**/*.{ts,tsx,vue}',
    './app/**/*.{ts,tsx,vue}',
    './src/**/*.{ts,tsx,vue}',
	],
  
  theme: {
    fontFamily: {
      sans: ['Montserrat', 'sans-serif']
    },
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        'base-white': 'hsl(var(--base-white))',
        'base-black': 'hsl(var(--base-black))',
        base: {
          white: 'hsl(var(--base-white))',
          black: 'hsl(var(--base-black))',
          background: 'hsl(var(--base-background))',
          menu: 'hsl(var(--base-menu))',
          menuHover: 'hsl(var(--base-menu-hover))',
        },
        brand: {
          100: 'hsl(var(--brand-100))',
          200: 'hsl(var(--brand-200))',
          600: 'hsl(var(--brand-600))',
          700: 'hsl(var(--brand-700))',
          800: 'hsl(var(--brand-800))',
          900: 'hsl(var(--brand-900))',
        },
        'gray-warm': {
          25: 'hsl(var(--gray-warm-25))',
          50: 'hsl(var(--gray-warm-50))',
          100: 'hsl(var(--gray-warm-100))',
          200: 'hsl(var(--gray-warm-200))',
          300 : 'hsl(var(--gray-warm-300))',
          400: 'hsl(var(--gray-warm-400))',
          500: 'hsl(var(--gray-warm-500))',
          600: 'hsl(var(--gray-warm-600))',
          700: 'hsl(var(--gray-warm-700))',
          800: 'hsl(var(--gray-warm-800))',
          900: 'hsl(var(--gray-warm-900))',
          950: 'hsl(var(--gray-warm-950))',
        },
        error: {
          25: 'hsl(var(--error-25))',
          50: 'hsl(var(--error-50))',
          100: 'hsl(var(--error-100))',
          200: 'hsl(var(--error-200))',
          300: 'hsl(var(--error-300))',
          400: 'hsl(var(--error-400))',
          500: 'hsl(var(--error-500))',
          600: 'hsl(var(--error-600))',
          700: 'hsl(var(--error-700))',
          800: 'hsl(var(--error-800))',
          900: 'hsl(var(--error-900))',
          950: 'hsl(var(--error-950))',
        },
        success: {
          25: 'hsl(var(--success-25))',
          50: 'hsl(var(--success-50))',
          100: 'hsl(var(--success-100))',
          200: 'hsl(var(--success-200))',
          300: 'hsl(var(--success-300))',
          400: 'hsl(var(--success-400))',
          500: 'hsl(var(--success-500))',
          600: 'hsl(var(--success-600))',
          700: 'hsl(var(--success-700))',
          800: 'hsl(var(--success-800))',
          900: 'hsl(var(--success-900))',
          950: 'hsl(var(--success-950))',
        },
        warning: {
          25: 'hsl(var(--warning-25))',
          50: 'hsl(var(--warning-50))',
          100: 'hsl(var(--warning-100))',
          200: 'hsl(var(--warning-200))',
          300: 'hsl(var(--warning-300))',
          400: 'hsl(var(--warning-400))',
          500: 'hsl(var(--warning-500))',
          600: 'hsl(var(--warning-600))',
          700: 'hsl(var(--warning-700))',
          800: 'hsl(var(--warning-800))',
          900: 'hsl(var(--warning-900))',
          950: 'hsl(var(--warning-950))',
        },
        info: {
          25: 'hsl(var(--info-25))',
          50: 'hsl(var(--info-50))',
          100: 'hsl(var(--info-100))',
          200: 'hsl(var(--info-200))',
          300: 'hsl(var(--info-300))',
          400: 'hsl(var(--info-400))',
          500: 'hsl(var(--info-500))',
          600: 'hsl(var(--info-600))',
          700: 'hsl(var(--info-700))',
          800: 'hsl(var(--info-800))',
          900: 'hsl(var(--info-900))',
          950: 'hsl(var(--info-950))',
        },
        'secondary-1': {
          400: 'hsl(var(--secondary1-400))',
          500: 'hsl(var(--secondary1-500))',
          600: 'hsl(var(--secondary1-600))',
        },
        'secondary-2': {
          400: 'hsl(var(--secondary2-400))',
          500: 'hsl(var(--secondary2-500))',
          600: 'hsl(var(--secondary2-600))',
        },
        'secondary-3': {
          400: 'hsl(var(--secondary3-400))',
          500: 'hsl(var(--secondary3-500))',
          600: 'hsl(var(--secondary3-600))',
        },
        'badges-purple': {
          200: 'hsl(var(--badges-purple-200))',
          700: 'hsl(var(--badges-purple-700))',
        },
        'badges-indigo': {
          200: 'hsl(var(--badges-indigo-200))',
          700: 'hsl(var(--badges-indigo-700))',
        },
        'badges-violet': {
          200: 'hsl(var(--badges-violet-200))',
          600: 'hsl(var(--badges-violet-600))',
          700: 'hsl(var(--badges-violet-700))',
          900: 'hsl(var(--badges-violet-900))',
        },
      },
      spacing: {
        'spacing-0': 'var(--spacing-0)',
        'spacing-0-5': 'var(--spacing-0-5)',
        'spacing-1': 'var(--spacing-1)',
        'spacing-2': 'var(--spacing-2)',
        'spacing-3': 'var(--spacing-3)',
        'spacing-4': 'var(--spacing-4)',
        'spacing-5': 'var(--spacing-5)',
        'spacing-6': 'var(--spacing-6)',
        'spacing-8': 'var(--spacing-8)',
        'spacing-10': 'var(--spacing-10)',
        'spacing-12': 'var(--spacing-12)',
        'spacing-16': 'var(--spacing-16)',
        'spacing-20': 'var(--spacing-20)',
        'spacing-24': 'var(--spacing-24)',
        'spacing-32': 'var(--spacing-32)',
        'spacing-40': 'var(--spacing-40)',
        'spacing-48': 'var(--spacing-48)',
        'spacing-56': 'var(--spacing-56)',
        'spacing-64': 'var(--spacing-64)',
        'spacing-80': 'var(--spacing-80)',
        'spacing-96': 'var(--spacing-96)',
        'spacing-120': 'var(--spacing-120)',
        'spacing-140': 'var(--spacing-140)',
        'spacing-160': 'var(--spacing-160)',
        'spacing-180': 'var(--spacing-180)',
        'spacing-192': 'var(--spacing-192)',
        'spacing-256': 'var(--spacing-256)',
        'spacing-320': 'var(--spacing-320)',
        'spacing-360': 'var(--spacing-360)',
        'spacing-400': 'var(--spacing-400)',
        'spacing-480': 'var(--spacing-480)',
      },
      borderRadius: {
        'radius-none': 'var(--radius-none)',
        'radius-xxs': 'var(--radius-xxs)',
        'radius-xs': 'var(--radius-xs)',
        'radius-sm': 'var(--radius-sm)',
        'radius-md': 'var(--radius-md)',
        'radius-lg': 'var(--radius-lg)',
        'radius-xl': 'var(--radius-xl)',
        'radius-2xl': 'var(--radius-2xl)',
        'radius-3xl': 'var(--radius-3xl)',
        'radius-4xl': 'var(--radius-4xl)',
        'radius-full': 'var(--radius-full)',
      },
      boxShadow: {
        'shadow-xs': 'var(--shadow-xs)',
        'shadow-sm': 'var(--shadow-sm)',
        'shadow-md': 'var(--shadow-md)',
        'shadow-lg': 'var(--shadow-lg)',
        'shadow-xl': 'var(--shadow-xl)',
        'shadow-2xl': 'var(--shadow-2xl)',
        'shadow-3xl': 'var(--shadow-3xl)',
      },
      ringWidth: {
        'ring-brand-shadow-xs': 'var(--ring-brand-shadow-xs)',
        'ring-brand-shadow-sm': 'var(--ring-brand-shadow-sm)',
      },
    },
  },
  plugins: [animate],
}