// Code generated by protoc-gen-go-grpc-mock (https://github.com/nefixestrada/protoc-gen-go-grpc-mock). DO NOT EDIT.
// version: v0.2.0

package auth

import (
	context "context"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
	net "net"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// NewAuthServiceMock creates and starts a Auth service mock.
// it returns the mock and a client for the
func NewAuthServiceMock() (*AuthServiceMock, AuthClient, error) {
	addr, err := net.ResolveTCPAddr("tcp", "localhost:0")
	if err != nil {
		return nil, nil, err
	}

	lis, err := net.ListenTCP("tcp", addr)
	if err != nil {
		return nil, nil, err
	}

	s := grpc.NewServer()
	m := &AuthServiceMock{server: s}

	RegisterAuthServer(s, m)

	go s.Serve(lis)

	cc, err := grpc.Dial(lis.Addr().String(), grpc.WithInsecure())
	if err != nil {
		return nil, nil, err
	}
	m.cc = cc

	cli := NewAuthClient(cc)

	return m, cli, nil
}

// AuthServiceMock is a mock for the AuthService service.
type AuthServiceMock struct {
	mock.Mock
	server *grpc.Server
	cc     *grpc.ClientConn
	UnimplementedAuthServer
}

func (m *AuthServiceMock) Stop() {
	m.cc.Close()
	m.server.Stop()
}

const Login = "Login"

func (m *AuthServiceMock) Login(ctx context.Context, in *LoginRequest) (*LoginResponse, error) {
	args := m.Called(ctx, in)
	return args.Get(0).(*LoginResponse), args.Error(1)
}

const Logout = "Logout"

func (m *AuthServiceMock) Logout(ctx context.Context, in *LogoutRequest) (*LogoutResponse, error) {
	args := m.Called(ctx, in)
	return args.Get(0).(*LogoutResponse), args.Error(1)
}

const Check = "Check"

func (m *AuthServiceMock) Check(ctx context.Context, in *CheckRequest) (*CheckResponse, error) {
	args := m.Called(ctx, in)
	return args.Get(0).(*CheckResponse), args.Error(1)
}

const Refresh = "Refresh"

func (m *AuthServiceMock) Refresh(ctx context.Context, in *RefreshRequest) (*RefreshRequest, error) {
	args := m.Called(ctx, in)
	return args.Get(0).(*RefreshRequest), args.Error(1)
}

const GetUserID = "GetUserID"

func (m *AuthServiceMock) GetUserID(ctx context.Context, in *GetUserIDRequest) (*GetUserIDResponse, error) {
	args := m.Called(ctx, in)
	return args.Get(0).(*GetUserIDResponse), args.Error(1)
}
