with-expecter: true
inpackage: true
filename: "testing_{{.InterfaceName | snakecase}}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
# Opt in to v3 defaults to silence mockery v2 deprecation warnings.
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  gitlab.com/isard/isardvdi/authentication/authentication:
    interfaces:
      Interface:
        config:
          mockname: "Mock{{ .PackageName | camelcase }}"
  gitlab.com/isard/isardvdi/authentication/provider:
    interfaces:
      Provider: {}
      ConfigurableProvider: {}
      BrandingAwareProvider: {}
  gitlab.com/isard/isardvdi/authentication/providermanager:
    interfaces:
      Interface:
        config:
          mockname: "Mock{{ .PackageName | camelcase }}"
  gitlab.com/isard/isardvdi/haproxy-sync/acme:
    interfaces:
      Interface:
        config:
          mockname: "Mock{{ .PackageName | camelcase }}"
  gitlab.com/isard/isardvdi/haproxy-sync/haproxy:
    interfaces:
      Interface:
        config:
          mockname: "Mock{{ .PackageName | camelcase }}"
  gitlab.com/isard/isardvdi/haproxy-sync/haproxy-sync:
    interfaces:
      Interface:
        config:
          mockname: "Mock{{ .PackageName | camelcase }}"
  gitlab.com/isard/isardvdi/sessions/sessions:
    interfaces:
      Interface:
        config:
          mockname: "Mock{{ .PackageName | camelcase }}"
  gitlab.com/isard/isardvdi/pkg/gen/oas/apiv4:
    interfaces:
      Invoker: {}
  gitlab.com/isard/isardvdi/pkg/gen/oas/notifier:
    interfaces:
      Invoker: {}
  gitlab.com/isard/isardvdi/pkg/gen/oas/authentication:
    interfaces:
      Invoker: {}
      Handler: {}
