version: "3.5"
services:
  isard-database:
    container_name: isard-database-devel
    ports:
      - "8080:8080"      
      - "28015:28015"
    restart: "no"

  isard-nginx:
    container_name: isard-nginx-devel
    volumes:
      - "/opt/isard/devel/dockers/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/opt/isard/devel/src/webapp/static/viewers:/viewers"
      - "/opt/isard/devel/dockers/nginx/errors:/errors"
      - "/opt/isard/devel/dockers/nginx/dh.pem:/dh.pem"
      - "/opt/isard/devel/dockers/nginx/auto-generate-certs.sh:/opt/auto-generate-certs.sh"
      - "/opt/isard/devel/dockers/nginx/entrypoint.sh:/opt/entrypoint.sh"
    image: isard/nginx:${DEVELTAG:-latest}
    build:
      target: development
    restart: "no"

  isard-hypervisor:
    # Uncomment following line to avoid hypervisor to be started
    # image: hello-world
    restart: none
    container_name: isard-hypervisor-devel
    ports:
      - "2022:22"
    volumes:
      - "/opt/isard/dockers/hypervisor/reset-hyper.sh:/reset-hyper.sh"
      - "/opt/isard/dockers/hypervisor/start_proxy.py:/start_proxy.py"
    image: isard/hypervisor:${DEVELTAG:-latest}
    build:
      target: development
    restart: "no"
        
  isard-app:
    container_name: isard-app-devel
    ports:
      - "5000:5000"       
      - "5555:5555"
    volumes:
      - "/opt/isard/devel/src/:/isard"
    image: isard/app:${DEVELTAG:-latest}
    build:
      target: development
    restart: "no"
