FROM python:3.5-slim
MAINTAINER isard <info@isard.com>

ENV INSTALL_PATH /isard
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH

COPY ./install/docker/requirements.pip3 requirements.pip3
RUN pip3 install -r requirements.pip3
COPY . .
COPY ./install/docker/isard.conf ./isard.conf
CMD python3 /isard/run_engine.py
