version: "3.2"
services:
  isard-grafana:
    volumes:
      - type: bind
        source: /opt/isard/grafana/grafana/data
        target: /grafana/data
        read_only: false
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    networks:
      - isard_network
    image: isard/grafana:1.1
    restart: always

networks:
  isard_network:
    external: false
