version: "3.5"
services:
  isard-hypervisor:
    container_name: isard-hypervisor
    volumes:
      - "/opt/isard/sshkeys/$HOSTNAME:/root/.ssh"
      - "/opt/isard:/isard"
      - "/opt/isard/certs/default:/etc/pki/libvirt-spice"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "2022:22"
      - "5900-6199:5900-6199"
      - "6400-6699:6400-6699"
    networks:
      - default
#      - internet-vms
    image: isard/hypervisor:${TAG:-latest}
    build:
      context: .
      dockerfile: dockers/hypervisor/Dockerfile    
    env_file:
      - config.env
    privileged: true
    restart: "no"
#networks:
#  internet-vms:
#    driver: macvlan
#    driver_opts:
#      parent: viewers
#    ipam:
#      config:
#        - subnet: 172.30.0.0/16
