#!/usr/bin/env python3

import os
import time

import redis


def wait_for_redis(host, port, password):
    while True:
        try:
            r = redis.StrictRedis(host=host, port=port, password=password)
            if r.ping():
                print("Redis is ready!")
                break
        except redis.ConnectionError:
            print(f"Redis not ready at {host}:{port}, retrying in 2 seconds...")
            time.sleep(2)


if __name__ == "__main__":
    redis_host = os.getenv("REDIS_HOST", "isard-redis")
    redis_port = int(os.getenv("REDIS_PORT", 6379))
    redis_password = os.getenv("REDIS_PASSWORD", None)

    wait_for_redis(redis_host, redis_port, redis_password)
