FROM python:3.5-slim
MAINTAINER isard <info@isard.com>

ENV INSTALL_PATH /isard
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH

COPY ./install/docker/requirements.pip3 requirements.pip3
RUN pip3 install -r requirements.pip3
RUN apt-get update -y
RUN apt-get install libvirt-dev libssl-dev gcc -y
RUN pip3 install libvirt-python==2.5.0 pexpect paramiko lxml xmltodict
COPY . .
COPY ./install/docker/isard.conf ./isard.conf
CMD python3 /isard/run_engine.py
