#!/usr/bin/env python3
#
#   IsardVDI - Open Source KVM Virtual Desktops based on KVM Linux and dockers
#   Copyright (C) 2026 IsardVDI
#
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Generate per-table subscriber classes for the IsardVDI changefeed.

Reads ``component/changefeed/src/tables.json`` and emits a Python package
at the requested output directory with one subscriber class per table.
Each subscriber provides ``parse()``, ``parse_dict()`` and ``serialize()``
methods that return the **concrete** envelope type — giving consumers full
type safety without a generic ``BaseModel`` return.

The generated ``__init__.py`` re-exports every subscriber and provides a
``TABLE_TO_SUBSCRIBER`` dict for dynamic dispatch.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

from changefeed_utils import camel as _camel


def _header(tables_hash: str) -> str:
    return f"# Auto-generated by gen_changefeed_subscribers.py -- DO NOT EDIT\n# tables.json sha256: {tables_hash}\n"


def _subscriber_source(table: str, *, has_stream: bool, tables_hash: str) -> str:
    camel = _camel(table)
    envelope_cls = f"{camel}ChangeEnvelope"
    envelope_module = f"changefeed_models.{table}_change_envelope"

    stream_attr = f'    STREAM: str = "stream:{table}"\n' if has_stream else ""

    return f"""{_header(tables_hash)}
from __future__ import annotations

from typing import Any

from {envelope_module} import {envelope_cls}


class {camel}Subscriber:
    TABLE: str = "{table}"
    CHANNEL: str = "{table}"
{stream_attr}
    @staticmethod
    def parse(raw: str | bytes) -> {envelope_cls}:
        if isinstance(raw, (bytes, bytearray)):
            raw = raw.decode("utf-8")
        return {envelope_cls}.model_validate_json(raw)

    @staticmethod
    def parse_dict(data: dict[str, Any]) -> {envelope_cls}:
        return {envelope_cls}.model_validate(data)

    @staticmethod
    def serialize(change: dict[str, Any]) -> str:
        envelope = {envelope_cls}.model_validate(
            {{"table": "{table}", "change": change}}
        )
        return envelope.model_dump_json()
"""


def _init_source(tables: list[dict[str, Any]], *, tables_hash: str) -> str:
    imports: list[str] = []
    entries: list[str] = []

    for entry in sorted(tables, key=lambda e: e["table"]):
        table = entry["table"]
        camel = _camel(table)
        cls_name = f"{camel}Subscriber"
        imports.append(f"from changefeed_subscribers.{table} import {cls_name}")
        entries.append(f'    "{table}": {cls_name},')

    imports_block = "\n".join(imports)
    entries_block = "\n".join(entries)

    return f"""{_header(tables_hash)}
from __future__ import annotations

from typing import Any, ClassVar, Protocol

{imports_block}


class SubscriberProtocol(Protocol):
    TABLE: ClassVar[str]
    CHANNEL: ClassVar[str]

    @staticmethod
    def parse(raw: str | bytes) -> Any: ...

    @staticmethod
    def parse_dict(data: dict[str, Any]) -> Any: ...

    @staticmethod
    def serialize(change: dict[str, Any]) -> str: ...


TABLE_TO_SUBSCRIBER: dict[str, type[SubscriberProtocol]] = {{
{entries_block}
}}
"""


def generate(tables: list[dict[str, Any]], output_dir: Path, tables_hash: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    for entry in tables:
        table = entry["table"]
        has_stream = bool(entry.get("stream"))
        source = _subscriber_source(
            table, has_stream=has_stream, tables_hash=tables_hash
        )
        (output_dir / f"{table}.py").write_text(source, encoding="utf-8")

    init_source = _init_source(tables, tables_hash=tables_hash)
    (output_dir / "__init__.py").write_text(init_source, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--tables", type=Path, required=True, help="Path to tables.json"
    )
    parser.add_argument(
        "--output-dir", type=Path, required=True, help="Output package directory"
    )
    args = parser.parse_args()

    raw = args.tables.read_bytes()
    tables_hash = hashlib.sha256(raw).hexdigest()[:12]
    tables = json.loads(raw)

    generate(tables, args.output_dir, tables_hash)

    print(
        f"Generated {len(tables)} subscriber(s) + __init__.py " f"in {args.output_dir}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
