version: '2'
services:
    isard-database:
        hostname: isard-database
        volumes:
            - "/opt/isard/database:/data"
        networks:
            - isard_network
        ##### - only devel - ############################
        ports:
            - "8080:8080"
        expose:
            - "28015"
        #################################################
        #aliases:
        #    - rethinkdb
        image: "rethinkdb"
        restart: "no"

    isard-nginx:
        volumes:
            - "/opt/isard/certs/default:/etc/nginx/external"
            - "/opt/isard/logs/nginx:/var/log/nginx"
        build:
            context: .
            dockerfile: dockers/nginx/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        networks:
            - isard_network
        image: isard/nginx:${TAG_DEVEL}
        restart: "no"
        depends_on:
          - "isard-app"

    isard-hypervisor:
        volumes:
            - "sshkeys:/root/.ssh"
            - "/opt/isard:/isard"
            - "/opt/isard/certs/default:/etc/pki/libvirt-spice"
        ports:
            - "5900-5949:5900-5949"
            - "55900-55949:55900-55949"
        ################ only for devel ###############
        expose:
            - "22"
        ###############################################
        networks:
            - isard_network
        image: "isard/hypervisor:${TAG_DEVEL}"
        privileged: true
        restart: "no"

    isard-app:
        hostname: isard-app
        volumes:
            ##### - only devel - ############################
            - "/opt/isard_devel/src:/isard"
            - "/opt/ipython_profile_default:/root/.ipython/profile_default"
            #################################################
            - "sshkeys:/root/.ssh"
            - "/opt/isard/certs:/certs"
            - "/opt/isard/logs:/isard/logs"
            - "/opt/isard/backups:/isard/backups"
            - "/opt/isard/uploads:/isard/uploads"
            - "/opt/isard/database/wizard:/isard/install/wizard"
        ########### - only devel #################
        expose:
            - "5000"
        ##########################################
        extra_hosts:
            - "isard-engine:127.0.0.1"
        networks:
            - isard_network
        image: "isard/app-devel:${TAG_DEVEL}"
        restart: "no"
        depends_on:
            - "isard-database"
            - "isard-hypervisor"

volumes:
    sshkeys:

networks:
    isard_network:
        external: false
