package_name_override: isardvdi_apiv4_client
project_name_override: isardvdi-apiv4-client
use_path_prefixes_for_title_model_names: false
field_constraints:
  allow_additional_properties: true
post_hooks:
  - ruff check . --fix --exit-zero
  - ruff format .
