// Code generated by "stringer -type=DesktopOSType -trimprefix=DesktopOSType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DesktopOSTypeUnknown-0]
	_ = x[DesktopOSTypeXEN-1]
	_ = x[DesktopOSTypeXENPVH-2]
	_ = x[DesktopOSTypeHVM-3]
	_ = x[DesktopOSTypeEXE-4]
}

const _DesktopOSType_name = "UnknownXENXENPVHHVMEXE"

var _DesktopOSType_index = [...]uint8{0, 7, 10, 16, 19, 22}

func (i DesktopOSType) String() string {
	if i < 0 || i >= DesktopOSType(len(_DesktopOSType_index)-1) {
		return "DesktopOSType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DesktopOSType_name[_DesktopOSType_index[i]:_DesktopOSType_index[i+1]]
}
