// Code generated by "stringer -type=DesktopBootType -trimprefix=DesktopBootType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DesktopBootTypeUnknown-0]
	_ = x[DesktopBootTypeFD-1]
	_ = x[DesktopBootTypeHD-2]
	_ = x[DesktopBootTypeCDROM-3]
	_ = x[DesktopBootTypeNetwork-4]
}

const _DesktopBootType_name = "UnknownFDHDCDROMNetwork"

var _DesktopBootType_index = [...]uint8{0, 7, 9, 11, 16, 23}

func (i DesktopBootType) String() string {
	if i < 0 || i >= DesktopBootType(len(_DesktopBootType_index)-1) {
		return "DesktopBootType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DesktopBootType_name[_DesktopBootType_index[i]:_DesktopBootType_index[i+1]]
}
