with-expecter: true
inpackage: true
filename: "testing_{{.InterfaceName | snakecase}}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
# Opt in to v3 defaults to silence mockery v2 deprecation warnings.
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  gitlab.com/isard/isardvdi/pkg/sdk:
    interfaces:
      Interface:
        config:
          mockname: "Mock{{ .PackageName | camelcase }}"
