{
 "title": "IsardVDI Usage",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "hypers", "label": "Hypervisors", "query": { "query": "label_values(hypervisor)" } },
   { "name": "domain", "label": "Host", "query": { "query": "label_values(domain)" } }
  ]
 },
 "panels": [
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$hypers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "hypers",
   "collapsed": true,
   "panels": [
    {
     "title": "Usuaris por Categoria",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_values by(category) (\"categoria\", isardvdi_isardvdi_api_user_info{domain=\"$domain\"})",
       "legendFormat": "{{category}}"
      }
     ]
    },
    {
     "title": "Escriptoris per Categoria",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "isardvdi_isardvdi_api_desktop_number_category{domain=\"$domain\"}",
       "legendFormat": "{{category}}"
      }
     ]
    },
    {
     "title": "Plantilles per Categoria",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "isardvdi_isardvdi_api_template_number_category{domain=\"$domain\"}",
       "legendFormat": "{{category}}"
      }
     ]
    },
    {
     "title": "/ Espai en disc",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{domain=\"$domain\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{domain=\"$domain\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    }
   ]
  }
 ]
}