{
 "title": "IsardVDI Storage",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "hypers", "label": "Hypervisors", "query": { "query": "label_values(hypervisor)" } },
   { "name": "domain", "label": "Host", "query": { "query": "label_values(domain)" } }
  ]
 },
 "panels": [
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$hypers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "hypers",
   "collapsed": true,
   "panels": [
    {
     "title": "/ Espai en disc",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
     "repeat": "domain",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{domain=\"$domain\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{domain=\"$domain\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "/opt/isard usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes{domain=\"$domain\", mountpoint=\"/opt/isard\", fstype!=\"rootfs\"} * 100 / node_filesystem_size_bytes{domain=\"$domain\", mountpoint=\"/opt/isard\", fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "Espai en disc",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 18, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{domain=\"$domain\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{domain=\"$domain\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "/opt/isard/groups usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes{domain=\"$domain\", mountpoint=\"/opt/isard/groups\", fstype!=\"rootfs\"} * 100 / node_filesystem_size_bytes{domain=\"$domain\", mountpoint=\"/opt/isard/groups\", fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "/opt/isard/templates usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes{domain=\"$domain\", mountpoint=\"/opt/isard/templates\", fstype!=\"rootfs\"} * 100 / node_filesystem_size_bytes{domain=\"$domain\", mountpoint=\"/opt/isard/templates\", fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "/opt/isard/media usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes{domain=\"$domain\", mountpoint=\"/opt/isard/media\", fstype!=\"rootfs\"} * 100 / node_filesystem_size_bytes{domain=\"$domain\", mountpoint=\"/opt/isard/media\", fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "/opt/isard/volatile usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes{domain=\"$domain\", mountpoint=\"/opt/isard/volatile\", fstype!=\"rootfs\"} * 100 / node_filesystem_size_bytes{domain=\"$domain\", mountpoint=\"/opt/isard/volatile\", fstype!=\"rootfs\"})"
      }
     ]
    }
   ]
  }
 ]
}