{
 "title": "IsardVDI Rethinkdb",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server_var", "label": "Server", "query": { "query": "label_values(server)" } },
   { "name": "db_var", "label": "Database", "query": { "query": "label_values(db)" } },
   {
    "name": "table_var",
    "label": "Table",
    "query": {
     "query": "label_values({db=~\"$db_var\"}, table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Stats collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stat collection duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "rethinkdb_scrape_latency", "legendFormat": "duration" }
   ]
  },
  {
   "title": "Stat collection errors count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rethinkdb_scrape_errors", "legendFormat": "errors count" }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Docs per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_cluster_docs_per_second",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Cluster client connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_cluster_client_connections",
     "legendFormat": "connections count"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_server_queries_per_second{server=~\"$server_var\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Server Docs Read per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_server_docs_per_second{server=~\"$server_var\", operation=\"read\"}",
     "legendFormat": "{{server}}::{{operation}}"
    }
   ]
  },
  {
   "title": "Server client connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_server_client_connections{server=~\"$server_var\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Server Docs Written per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_server_docs_per_second{server=~\"$server_var\", operation=\"written\"}",
     "legendFormat": "{{server}}::{{operation}}"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table Docs per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_table_docs_per_second{db=~\"$db_var\", table=~\"$table_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}"
    }
   ]
  },
  {
   "title": "Table replica Docs per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_tablereplica_docs_per_second{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}::{{server}}"
    }
   ]
  },
  {
   "title": "Table replica disk io bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rethinkdb_tablereplica_io{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}::{{server}}"
    }
   ]
  },
  {
   "title": "Table replica Disk data bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rethinkdb_tablereplica_data_bytes{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{server}}"
    }
   ]
  }
 ]
}