{
 "title": "IsardVDI Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hypers",
    "label": "Hypervisors",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(\n  bucket: \"isardvdi-go\",\n  measurement: \"hypervisor\",\n  tag: \"hypervisor\"\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Desktops started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"isardvdi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"domains\"\n  )\n  |> keep(columns: [\"_time\", \"id_domain\"])\n  |> group()\n  |> unique(column: \"id_domain\")\n  |> count(column: \"id_domain\")\n  |> yield()"
    }
   ]
  },
  { "title": "$hypers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "hypers" },
  {
   "title": "Desktops started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"isardvdi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"domains\" and\n    r[\"hypervisor\"] == \"${hypers}\"\n  )\n  |> keep(columns: [\"_time\", \"id_domain\"])\n  |> group()\n  |> unique(column: \"id_domain\")\n  |> count(column: \"id_domain\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "/opt/isard usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fs",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "mnt_point", "operator": "=", "value": "/opt/isard" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$hypers$/" }
     ]
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"isardvdi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"domains\" and\n    r[\"hypervisor\"] == \"${hypers}\" and\n    r[\"_field\"] == \"vcpus_current\"\n  )\n  |> group(columns: [\"id_domain\"])\n  |> sort(columns: [\"_time\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sum()\n"
    }
   ]
  },
  {
   "title": "CPU LOAD",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"system\" and\n    r[\"hypervisor\"] == \"${hypers}\" and\n    r[\"_field\"] == \"cpu_usage\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> last()\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"system\" and\n    r[\"hypervisor\"] == \"${hypers}\" and\n    r[\"_field\"] == \"cpu_usage\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield()\n"
    }
   ]
  },
  { "title": "vCPU/CPU ratio", "type": "stat", "gridPos": { "h": 4, "w": 2, "x": 9, "y": 9 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  {
   "title": "Sockets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByMetric(isard.sysstats.$hypers.system.cpu.sockets.*)"
    }
   ]
  },
  { "title": "Hypervisor Hardware", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 0, "y": 13 } },
  {
   "title": "vRAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "isard.hypers.$hypers.stats.num_domains"
    }
   ]
  },
  {
   "title": "RAM LOAD",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"isardvdi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"hypervisors\" and\n    r[\"hypervisor\"] == \"${hypers}\" and\n    r[\"_field\"] =~ /memory_(total|free|cached)/\n  )\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    _time: r[\"_time\"],\n    _value: 100.0 - (float(v: r[\"memory_free\"] + r[\"memory_cached\"]) / float(v: r[\"memory_total\"]) * 100.0)\n  }))\n  |> last()\n",
     "target": "isard.sysstats.$hypers.system.mem.perc"
    }
   ]
  },
  {
   "title": "RAM %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"isardvdi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"hypervisors\" and\n    r[\"hypervisor\"] == \"${hypers}\" and\n    r[\"_field\"] =~ /memory_(total|free|cached)/\n  )\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    _time: r[\"_time\"],\n    _value: 100.0 - (float(v: r[\"memory_free\"] + r[\"memory_cached\"]) / float(v: r[\"memory_total\"]) * 100.0)\n  }))\n"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"system\" and\n    r[\"hypervisor\"] == \"${hypers}\" and\n    r[\"_field\"] == \"cpu_cores\"\n  )\n  |> last()\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"system\" and\n    r[\"hypervisor\"] == \"${hypers}\" and\n    r[\"_field\"] == \"cpu_threads\"\n  )\n  |> last()\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "RAM/vRAM ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(divideSeries(isard.domains.global.memory, #A), 'ratio')",
     "targetFull": "alias(divideSeries(isard.domains.global.memory, alias(scale(isard.sysstats.$hypers.system.mem.total, 0.001), 'RAM')), 'ratio')"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"system\" and\n    r[\"hypervisor\"] == \"${hypers}\" and\n    r[\"_field\"] == \"cpu_frequency\"\n  )\n  |> last()\n  |> map(fn: (r) => ({\n      r with\n      _value: r._value * 1000.0 * 1000.0\n    })\n  )\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"isardvdi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"hypervisors\" and\n    r[\"hypervisor\"] == \"${hypers}\" and\n    r[\"_field\"] == \"memory_total\")\n  |> last()\n  |> map(fn: (r) => ({\n    _value: r[\"_value\"] * 1024\n  }))\n"
    }
   ]
  }
 ]
}