#
# Build phase
#
ARG GOLANG_BUILD_IMAGE=golang:1.25.8-alpine3.22@sha256:6b7607461f105ccaa0615b6f7932dfd5b36c5d827a0770b5578e565107cc3adb
ARG GOLANG_RUN_IMAGE=alpine:3.22@sha256:14358309a308569c32bdc37e2e0e9694be33a9d99e68afb0f5ff33cc1f695dce

FROM ${GOLANG_BUILD_IMAGE} as build

RUN apk add --no-cache \
    git

RUN git clone https://github.com/isard-vdi/rethinkdb-prometheus-exporter /build && \
    git -C /build checkout 3a5465834795a4272b0c776133dda284702fec58

WORKDIR /build

RUN go mod download

RUN CGO_ENABLED=0 go build -o rethinkdb-prometheus-exporter


#
# RethinkDB stats
#
FROM ${GOLANG_RUN_IMAGE}

RUN apk -U upgrade --no-cache

COPY --from=build /build/rethinkdb-prometheus-exporter /rethinkdb-prometheus-exporter

ENTRYPOINT [ "/rethinkdb-prometheus-exporter" ]
