#
# Build phase
#
FROM golang:1.19-alpine as build

RUN apk add --no-cache \
    git


RUN git clone https://github.com/rethinkdb/prometheus-exporter /build

WORKDIR /build

RUN go mod download

RUN CGO_ENABLED=0 go build -o rethinkdb-prometheus-exporter


#
# RethinkDB stats
#
FROM alpine:3.16

COPY --from=build /build/rethinkdb-prometheus-exporter /rethinkdb-prometheus-exporter

ENTRYPOINT [ "/rethinkdb-prometheus-exporter" ]
