version: "3.5"
services:
  isard-mosquitto:
    container_name: isard-mosquitto
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
    networks:
      - isard_network
    image: isard/mosquitto:1.1
    restart: always
      
networks:
  isard_network:
    external: false
    name: isard_network
