version: "3.5"
services:
  isard-api:
    environment:
      # This is also added in authentication.test.yml
      - AUTHENTICATION_AUTHENTICATION_LDAP_ENABLED=true
      - AUTHENTICATION_AUTHENTICATION_SAML_ENABLED=true
