services:
  isard-change-handler:
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: component/change-handler/docker/Dockerfile
      args:
        RETHINKDB_FORK_SHA: ${RETHINKDB_FORK_SHA:-unknown}
