services:
  isard-changefeed:
    environment:
      PYTHONPATH: /opt/isardvdi
    volumes:
      - ${BUILD_ROOT_PATH}/component/changefeed/src:/app
      - ${BUILD_ROOT_PATH}/component/_common/src/isardvdi_common:/opt/isardvdi/isardvdi_common
      - ${BUILD_ROOT_PATH}/pkg/gen/asyncapi/changefeed:/opt/isardvdi/asyncapi_changefeed
