version: '3.5'
services:
  isard-stats-rethinkdb:
    container_name: isard-stats-rethinkdb
    image: ${DOCKER_IMAGE_PREFIX}stats-rethinkdb:${DOCKER_IMAGE_TAG:-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.28
    command:
      - '--db.address'
      - 'isard-db:28015'
