services:
  isard-hypervisor:
    volumes:
    - ${BUILD_ROOT_PATH}/docker/hypervisor/src:/src
    - ${BUILD_ROOT_PATH}/component/_common/isardvdi_common:/src/isardvdi_common
    - ${BUILD_ROOT_PATH}/component/_common/isardvdi_apiv4_client/isardvdi_apiv4_client:/src/isardvdi_apiv4_client
    - ${BUILD_ROOT_PATH}/component/_common/isardvdi_apiv4_client/isardvdi_apiv4_client_auth:/src/isardvdi_apiv4_client_auth
    - ${BUILD_ROOT_PATH}/component/_common/isardvdi_notifier_client/isardvdi_notifier_client:/src/isardvdi_notifier_client
    - ${BUILD_ROOT_PATH}/component/_common/isardvdi_notifier_client/isardvdi_notifier_client_auth:/src/isardvdi_notifier_client_auth
    - ${BUILD_ROOT_PATH}/component/_common/isardvdi_scheduler_client/isardvdi_scheduler_client:/src/isardvdi_scheduler_client
    - ${BUILD_ROOT_PATH}/component/_common/isardvdi_scheduler_client/isardvdi_scheduler_client_auth:/src/isardvdi_scheduler_client_auth
    - ${BUILD_ROOT_PATH}/docker/hypervisor/kvm/hooks:/etc/libvirt/hooks
