services:
  isard-openapi:
    container_name: isard-openapi
    image: ${DOCKER_IMAGE_PREFIX}openapi:${DOCKER_IMAGE_TAG:-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.152
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--proxy-headers", "--forwarded-allow-ips=*"]
    healthcheck:
      test:
        - CMD
        - python3
        - -c
        - |
          import socket, sys
          s = socket.socket(); s.settimeout(2)
          try:
              s.connect(('localhost', 5000))
              sys.exit(0)
          except OSError:
              sys.exit(1)
          finally:
              s.close()
      start_period: 30s
      interval: 5s
    environment:
      HTTPS_PORT: ${HTTPS_PORT:-443}