services:
  isard-socketio:
    command: ["venv/bin/uvicorn", "isardvdi_socketio:app", "--host", "0.0.0.0", "--port", "5000", "--reload", "--reload-dir", "/opt/isardvdi"]
    volumes:
      - ${BUILD_ROOT_PATH}/component/socketio/src:/opt/isardvdi/isardvdi_socketio
      - ${BUILD_ROOT_PATH}/component/_common/isardvdi_common:/opt/isardvdi/isardvdi_common
