services:
  isard-storage:
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: docker/storage/Dockerfile
      target: production
      args:
        RETHINKDB_FORK_SHA: ${RETHINKDB_FORK_SHA:-unknown}
