version: '3.5'
services:
  isard-websockify:
    container_name: isard-websockify
    image: ${DOCKER_IMAGE_PREFIX}websockify:${DOCKER_IMAGE_TAG-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.27
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      API_DOMAIN:
      VIDEO_HYPERVISOR_HOSTNAMES:
      VIDEO_HYPERVISOR_PORTS:
