#!/usr/bin/env python3
"""Swap one interface id by another on every ``domains`` document, in place.

Replaces every entry of ``domains.create_dict.hardware.interfaces`` whose
``id`` equals ``--from`` with the same entry but ``id=<--to>``. The per-entry
``mac`` and the position within the list are preserved, so:

* Guest PCI slot ordering stays the same (the engine iterates the list with
  ``enumerate(...)`` at ``engine/models/domain_xml.py:1980-2045``).
* The MAC the guest OS sees does not change — ``mac`` is taken verbatim from
  ``list_interfaces_mac[interface_index]``.
* No other field on the domain needs to change. ``kind`` / ``model`` /
  ``net`` / ``qos_id`` / ``ifname`` are resolved live on every start by
  ``get_interface_cached(id)``, and the stored ``domains.xml`` field is
  regenerated by ``recreate_xml_to_start`` from ``create_dict``.

Domains that do not contain ``--from`` in their interfaces list are left
untouched. Running desktops keep their old NIC until the next stop+start.

Dry-run by default; pass ``--apply`` to commit. Idempotent (rerunning after
a successful apply touches nothing).

Run inside the api container::

    docker exec isard-api python3 /api/scripts/swap_domain_interface.py \\
        --from <src-interface-id> --to <dst-interface-id>

    # commit:
    docker exec isard-api python3 /api/scripts/swap_domain_interface.py \\
        --from <src-interface-id> --to <dst-interface-id> --apply

ALWAYS take a rethinkdb backup first::

    docker exec -ti isard-db sh -c \\
        "mkdir -p /data/backups; cd /data/backups; rethinkdb-dump; ls -lh"
"""

import argparse
import hashlib
import json
import os
import sys
import time

from rethinkdb import r

DB_HOST = os.environ.get("RETHINKDB_HOST", "isard-db")
DB_PORT = int(os.environ.get("RETHINKDB_PORT", "28015"))
DB_NAME = os.environ.get("RETHINKDB_DB", "isard")


def _mac_multiset_hash(conn):
    macs = []
    for d in r.table("domains").pluck("create_dict").run(conn):
        for i in (
            d.get("create_dict", {}).get("hardware", {}).get("interfaces", []) or []
        ):
            macs.append(i.get("mac", ""))
    macs.sort()
    return len(macs), hashlib.sha256("|".join(macs).encode()).hexdigest()


def _swap(conn, src, dst, apply_changes, log_path):
    todo = list(
        r.table("domains")
        .filter(
            lambda d: d["create_dict"]["hardware"]["interfaces"]["id"].contains(src)
        )
        .pluck("id", "kind", "create_dict")
        .run(conn)
    )
    print(f"  candidates: {len(todo)} domain(s) contain interface id={src!r}")

    ok = 0
    with open(log_path, "w") as f:
        for d in todo:
            old = d["create_dict"]["hardware"]["interfaces"]
            new = [
                {"id": dst if i["id"] == src else i["id"], "mac": i["mac"]} for i in old
            ]

            # invariants - abort the whole run if violated
            assert len(new) == len(old), d["id"]
            assert [i["mac"] for i in new] == [i["mac"] for i in old], d["id"]
            assert any(a["id"] != b["id"] for a, b in zip(old, new)), d["id"]

            entry = {
                "id": d["id"],
                "kind": d["kind"],
                "old": old,
                "new": new,
            }
            if not apply_changes:
                entry["dry"] = True
                f.write(json.dumps(entry) + "\n")
                ok += 1
                continue

            res = (
                r.table("domains")
                .get(d["id"])
                .update(
                    {"create_dict": {"hardware": {"interfaces": r.literal(new)}}},
                    non_atomic=True,
                )
                .run(conn)
            )
            entry["res"] = res
            if res.get("replaced") == 1 and res.get("errors", 0) == 0:
                ok += 1
                f.write(json.dumps(entry) + "\n")
            else:
                entry["ERROR"] = True
                f.write(json.dumps(entry) + "\n")
                print(f"  ERROR on {d['id']}: {res}", file=sys.stderr)
                return ok, False

    return ok, True


def main():
    parser = argparse.ArgumentParser(
        description="Swap one interface id by another on every domains doc, in place.",
    )
    parser.add_argument(
        "--from",
        dest="src",
        required=True,
        help="Source interface id to be replaced (e.g. 'default').",
    )
    parser.add_argument(
        "--to",
        dest="dst",
        required=True,
        help="Destination interface id to write in its place.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Commit changes. Without this flag the script is dry-run.",
    )
    parser.add_argument(
        "--log-dir",
        default="/data/backups",
        help="Directory where the per-doc log is written.",
    )
    args = parser.parse_args()

    if args.src == args.dst:
        parser.error("--from and --to must differ")

    conn = r.connect(host=DB_HOST, port=DB_PORT, db=DB_NAME)
    try:
        mode = "APPLY" if args.apply else "DRY-RUN"
        print(f"=== swap_domain_interface [{mode}] {args.src!r} -> {args.dst!r} ===")

        # Verify destination interface exists in the interfaces table
        if r.table("interfaces").get(args.dst).run(conn) is None:
            print(
                f"  ERROR: destination interface id {args.dst!r} not found in 'interfaces' table",
                file=sys.stderr,
            )
            return 2

        n0, h0 = _mac_multiset_hash(conn)
        print(f"  BEFORE  macs={n0} sha256={h0}")

        os.makedirs(args.log_dir, exist_ok=True)
        suffix = "dry" if not args.apply else "apply"
        log_path = os.path.join(
            args.log_dir,
            f"swap_domain_interface_{args.src}_to_{args.dst}_{time.strftime('%Y-%m-%dT%H-%M-%S')}.{suffix}.log",
        )

        ok, success = _swap(conn, args.src, args.dst, args.apply, log_path)
        if not success:
            print(
                f"  ABORTED after {ok} successful update(s). Log: {log_path}",
                file=sys.stderr,
            )
            return 2

        remaining = (
            r.table("domains")
            .filter(
                lambda d: d["create_dict"]["hardware"]["interfaces"]["id"].contains(
                    args.src
                )
            )
            .count()
            .run(conn)
        )
        dst_total = (
            r.table("domains")
            .filter(
                lambda d: d["create_dict"]["hardware"]["interfaces"]["id"].contains(
                    args.dst
                )
            )
            .count()
            .run(conn)
        )
        n1, h1 = _mac_multiset_hash(conn)

        print(
            f"  {'PLANNED' if not args.apply else 'APPLIED'}: {ok} doc(s)  log={log_path}"
        )
        print(
            f"  AFTER   remaining_src={remaining} dst_total={dst_total} macs={n1} sha256={h1}"
        )
        if args.apply:
            print(f"  MAC_INTEGRITY={'OK' if (n0, h0) == (n1, h1) else 'CHANGED'}")
            print("  (use a stop+start to push the change to running desktops)")
        else:
            print("  (no writes performed; rerun with --apply to commit)")
        return 0
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
