// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.14.0
// source: proto/controller/controller.proto

package controller

import (
	common "gitlab.com/isard/isardvdi/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DesktopListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopListRequest) Reset() {
	*x = DesktopListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_controller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopListRequest) ProtoMessage() {}

func (x *DesktopListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopListRequest.ProtoReflect.Descriptor instead.
func (*DesktopListRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{0}
}

type DesktopListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopListResponse) Reset() {
	*x = DesktopListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_controller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopListResponse) ProtoMessage() {}

func (x *DesktopListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopListResponse.ProtoReflect.Descriptor instead.
func (*DesktopListResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{1}
}

type DesktopStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DesktopStartRequest) Reset() {
	*x = DesktopStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_controller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest) ProtoMessage() {}

func (x *DesktopStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{2}
}

func (x *DesktopStartRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DesktopStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Viewer *common.Viewer `protobuf:"bytes,1,opt,name=viewer,proto3" json:"viewer,omitempty"`
}

func (x *DesktopStartResponse) Reset() {
	*x = DesktopStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_controller_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartResponse) ProtoMessage() {}

func (x *DesktopStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartResponse.ProtoReflect.Descriptor instead.
func (*DesktopStartResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{3}
}

func (x *DesktopStartResponse) GetViewer() *common.Viewer {
	if x != nil {
		return x.Viewer
	}
	return nil
}

type DesktopStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DesktopStopRequest) Reset() {
	*x = DesktopStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_controller_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStopRequest) ProtoMessage() {}

func (x *DesktopStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStopRequest.ProtoReflect.Descriptor instead.
func (*DesktopStopRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{4}
}

func (x *DesktopStopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DesktopStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopStopResponse) Reset() {
	*x = DesktopStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_controller_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStopResponse) ProtoMessage() {}

func (x *DesktopStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStopResponse.ProtoReflect.Descriptor instead.
func (*DesktopStopResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{5}
}

type ViewerGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ViewerGetRequest) Reset() {
	*x = ViewerGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_controller_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewerGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerGetRequest) ProtoMessage() {}

func (x *ViewerGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerGetRequest.ProtoReflect.Descriptor instead.
func (*ViewerGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{6}
}

func (x *ViewerGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ViewerGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Viewer *common.Viewer `protobuf:"bytes,1,opt,name=viewer,proto3" json:"viewer,omitempty"`
}

func (x *ViewerGetResponse) Reset() {
	*x = ViewerGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controller_controller_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewerGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerGetResponse) ProtoMessage() {}

func (x *ViewerGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerGetResponse.ProtoReflect.Descriptor instead.
func (*ViewerGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{7}
}

func (x *ViewerGetResponse) GetViewer() *common.Viewer {
	if x != nil {
		return x.Viewer
	}
	return nil
}

var File_proto_controller_controller_proto protoreflect.FileDescriptor

var file_proto_controller_controller_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x24, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e,
	0x69, 0x73, 0x61, 0x72, 0x64, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x76, 0x64, 0x69, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x1a, 0x0c, 0x76, 0x69, 0x65, 0x77, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x6b, 0x74,
	0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a,
	0x13, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x58, 0x0a, 0x14, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x76, 0x64, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x52, 0x06, 0x76,
	0x69, 0x65, 0x77, 0x65, 0x72, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x11, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x76,
	0x69, 0x65, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2e, 0x69,
	0x73, 0x61, 0x72, 0x64, 0x76, 0x64, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56,
	0x69, 0x65, 0x77, 0x65, 0x72, 0x52, 0x06, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x32, 0xa4, 0x04,
	0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x84, 0x01, 0x0a,
	0x0b, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x38, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2e,
	0x69, 0x73, 0x61, 0x72, 0x64, 0x76, 0x64, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x39, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x76,
	0x64, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x87, 0x01, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x39, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x76, 0x64, 0x69,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x3a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x73, 0x61,
	0x72, 0x64, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x76, 0x64, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x84, 0x01,
	0x0a, 0x0b, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x38, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64,
	0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x76, 0x64, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x6f, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x39, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64,
	0x76, 0x64, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x7e, 0x0a, 0x09, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x47, 0x65,
	0x74, 0x12, 0x36, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69,
	0x73, 0x61, 0x72, 0x64, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x76, 0x64, 0x69, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2e, 0x69, 0x73, 0x61,
	0x72, 0x64, 0x76, 0x64, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x2e, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2f, 0x69, 0x73, 0x61, 0x72, 0x64, 0x76, 0x64,
	0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_controller_controller_proto_rawDescOnce sync.Once
	file_proto_controller_controller_proto_rawDescData = file_proto_controller_controller_proto_rawDesc
)

func file_proto_controller_controller_proto_rawDescGZIP() []byte {
	file_proto_controller_controller_proto_rawDescOnce.Do(func() {
		file_proto_controller_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_controller_controller_proto_rawDescData)
	})
	return file_proto_controller_controller_proto_rawDescData
}

var file_proto_controller_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_controller_controller_proto_goTypes = []interface{}{
	(*DesktopListRequest)(nil),   // 0: com.gitlab.isard.isardvdi.controller.DesktopListRequest
	(*DesktopListResponse)(nil),  // 1: com.gitlab.isard.isardvdi.controller.DesktopListResponse
	(*DesktopStartRequest)(nil),  // 2: com.gitlab.isard.isardvdi.controller.DesktopStartRequest
	(*DesktopStartResponse)(nil), // 3: com.gitlab.isard.isardvdi.controller.DesktopStartResponse
	(*DesktopStopRequest)(nil),   // 4: com.gitlab.isard.isardvdi.controller.DesktopStopRequest
	(*DesktopStopResponse)(nil),  // 5: com.gitlab.isard.isardvdi.controller.DesktopStopResponse
	(*ViewerGetRequest)(nil),     // 6: com.gitlab.isard.isardvdi.controller.ViewerGetRequest
	(*ViewerGetResponse)(nil),    // 7: com.gitlab.isard.isardvdi.controller.ViewerGetResponse
	(*common.Viewer)(nil),        // 8: com.gitlab.isard.isardvdi.common.Viewer
}
var file_proto_controller_controller_proto_depIdxs = []int32{
	8, // 0: com.gitlab.isard.isardvdi.controller.DesktopStartResponse.viewer:type_name -> com.gitlab.isard.isardvdi.common.Viewer
	8, // 1: com.gitlab.isard.isardvdi.controller.ViewerGetResponse.viewer:type_name -> com.gitlab.isard.isardvdi.common.Viewer
	0, // 2: com.gitlab.isard.isardvdi.controller.Controller.DesktopList:input_type -> com.gitlab.isard.isardvdi.controller.DesktopListRequest
	2, // 3: com.gitlab.isard.isardvdi.controller.Controller.DesktopStart:input_type -> com.gitlab.isard.isardvdi.controller.DesktopStartRequest
	4, // 4: com.gitlab.isard.isardvdi.controller.Controller.DesktopStop:input_type -> com.gitlab.isard.isardvdi.controller.DesktopStopRequest
	6, // 5: com.gitlab.isard.isardvdi.controller.Controller.ViewerGet:input_type -> com.gitlab.isard.isardvdi.controller.ViewerGetRequest
	1, // 6: com.gitlab.isard.isardvdi.controller.Controller.DesktopList:output_type -> com.gitlab.isard.isardvdi.controller.DesktopListResponse
	3, // 7: com.gitlab.isard.isardvdi.controller.Controller.DesktopStart:output_type -> com.gitlab.isard.isardvdi.controller.DesktopStartResponse
	5, // 8: com.gitlab.isard.isardvdi.controller.Controller.DesktopStop:output_type -> com.gitlab.isard.isardvdi.controller.DesktopStopResponse
	7, // 9: com.gitlab.isard.isardvdi.controller.Controller.ViewerGet:output_type -> com.gitlab.isard.isardvdi.controller.ViewerGetResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_controller_controller_proto_init() }
func file_proto_controller_controller_proto_init() {
	if File_proto_controller_controller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_controller_controller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_controller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_controller_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_controller_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_controller_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_controller_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_controller_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewerGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_controller_controller_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewerGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_controller_controller_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_controller_controller_proto_goTypes,
		DependencyIndexes: file_proto_controller_controller_proto_depIdxs,
		MessageInfos:      file_proto_controller_controller_proto_msgTypes,
	}.Build()
	File_proto_controller_controller_proto = out.File
	file_proto_controller_controller_proto_rawDesc = nil
	file_proto_controller_controller_proto_goTypes = nil
	file_proto_controller_controller_proto_depIdxs = nil
}
