// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: pkg/proto/desktop-builder.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetXmlRequest_DesktopType int32

const (
	GetXmlRequest_DESKTOP_TYPE_UNKNOWN GetXmlRequest_DesktopType = 0
	GetXmlRequest_DESKTOP_TYPE_KVM     GetXmlRequest_DesktopType = 1 // TODO: Add the rest of the desktop-buildervisor drivers
)

// Enum value maps for GetXmlRequest_DesktopType.
var (
	GetXmlRequest_DesktopType_name = map[int32]string{
		0: "DESKTOP_TYPE_UNKNOWN",
		1: "DESKTOP_TYPE_KVM",
	}
	GetXmlRequest_DesktopType_value = map[string]int32{
		"DESKTOP_TYPE_UNKNOWN": 0,
		"DESKTOP_TYPE_KVM":     1,
	}
)

func (x GetXmlRequest_DesktopType) Enum() *GetXmlRequest_DesktopType {
	p := new(GetXmlRequest_DesktopType)
	*p = x
	return p
}

func (x GetXmlRequest_DesktopType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetXmlRequest_DesktopType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_desktop_builder_proto_enumTypes[0].Descriptor()
}

func (GetXmlRequest_DesktopType) Type() protoreflect.EnumType {
	return &file_pkg_proto_desktop_builder_proto_enumTypes[0]
}

func (x GetXmlRequest_DesktopType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetXmlRequest_DesktopType.Descriptor instead.
func (GetXmlRequest_DesktopType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 0}
}

type GetXmlRequest_DesktopOS_DesktopOSType_Arch int32

const (
	GetXmlRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_ARCH_UNKNOWN GetXmlRequest_DesktopOS_DesktopOSType_Arch = 0
	GetXmlRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_ARCH_X86_64  GetXmlRequest_DesktopOS_DesktopOSType_Arch = 1
)

// Enum value maps for GetXmlRequest_DesktopOS_DesktopOSType_Arch.
var (
	GetXmlRequest_DesktopOS_DesktopOSType_Arch_name = map[int32]string{
		0: "DESKTOP_OS_TYPE_ARCH_UNKNOWN",
		1: "DESKTOP_OS_TYPE_ARCH_X86_64",
	}
	GetXmlRequest_DesktopOS_DesktopOSType_Arch_value = map[string]int32{
		"DESKTOP_OS_TYPE_ARCH_UNKNOWN": 0,
		"DESKTOP_OS_TYPE_ARCH_X86_64":  1,
	}
)

func (x GetXmlRequest_DesktopOS_DesktopOSType_Arch) Enum() *GetXmlRequest_DesktopOS_DesktopOSType_Arch {
	p := new(GetXmlRequest_DesktopOS_DesktopOSType_Arch)
	*p = x
	return p
}

func (x GetXmlRequest_DesktopOS_DesktopOSType_Arch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetXmlRequest_DesktopOS_DesktopOSType_Arch) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_desktop_builder_proto_enumTypes[1].Descriptor()
}

func (GetXmlRequest_DesktopOS_DesktopOSType_Arch) Type() protoreflect.EnumType {
	return &file_pkg_proto_desktop_builder_proto_enumTypes[1]
}

func (x GetXmlRequest_DesktopOS_DesktopOSType_Arch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetXmlRequest_DesktopOS_DesktopOSType_Arch.Descriptor instead.
func (GetXmlRequest_DesktopOS_DesktopOSType_Arch) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 0, 0, 0}
}

type GetXmlRequest_DesktopOS_DesktopOSType_Machine int32

const (
	GetXmlRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_MACHINE_UNKNOWN GetXmlRequest_DesktopOS_DesktopOSType_Machine = 0
	GetXmlRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_MACHINE_PC      GetXmlRequest_DesktopOS_DesktopOSType_Machine = 1
	GetXmlRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_MACHINE_Q35     GetXmlRequest_DesktopOS_DesktopOSType_Machine = 2
)

// Enum value maps for GetXmlRequest_DesktopOS_DesktopOSType_Machine.
var (
	GetXmlRequest_DesktopOS_DesktopOSType_Machine_name = map[int32]string{
		0: "DESKTOP_OS_TYPE_MACHINE_UNKNOWN",
		1: "DESKTOP_OS_TYPE_MACHINE_PC",
		2: "DESKTOP_OS_TYPE_MACHINE_Q35",
	}
	GetXmlRequest_DesktopOS_DesktopOSType_Machine_value = map[string]int32{
		"DESKTOP_OS_TYPE_MACHINE_UNKNOWN": 0,
		"DESKTOP_OS_TYPE_MACHINE_PC":      1,
		"DESKTOP_OS_TYPE_MACHINE_Q35":     2,
	}
)

func (x GetXmlRequest_DesktopOS_DesktopOSType_Machine) Enum() *GetXmlRequest_DesktopOS_DesktopOSType_Machine {
	p := new(GetXmlRequest_DesktopOS_DesktopOSType_Machine)
	*p = x
	return p
}

func (x GetXmlRequest_DesktopOS_DesktopOSType_Machine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetXmlRequest_DesktopOS_DesktopOSType_Machine) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_desktop_builder_proto_enumTypes[2].Descriptor()
}

func (GetXmlRequest_DesktopOS_DesktopOSType_Machine) Type() protoreflect.EnumType {
	return &file_pkg_proto_desktop_builder_proto_enumTypes[2]
}

func (x GetXmlRequest_DesktopOS_DesktopOSType_Machine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetXmlRequest_DesktopOS_DesktopOSType_Machine.Descriptor instead.
func (GetXmlRequest_DesktopOS_DesktopOSType_Machine) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 0, 0, 1}
}

type GetXmlRequest_DesktopOS_DesktopOSType_Type int32

const (
	GetXmlRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_TYPE_UNKNOWN GetXmlRequest_DesktopOS_DesktopOSType_Type = 0
	GetXmlRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_TYPE_HVM     GetXmlRequest_DesktopOS_DesktopOSType_Type = 1
)

// Enum value maps for GetXmlRequest_DesktopOS_DesktopOSType_Type.
var (
	GetXmlRequest_DesktopOS_DesktopOSType_Type_name = map[int32]string{
		0: "DESKTOP_OS_TYPE_TYPE_UNKNOWN",
		1: "DESKTOP_OS_TYPE_TYPE_HVM",
	}
	GetXmlRequest_DesktopOS_DesktopOSType_Type_value = map[string]int32{
		"DESKTOP_OS_TYPE_TYPE_UNKNOWN": 0,
		"DESKTOP_OS_TYPE_TYPE_HVM":     1,
	}
)

func (x GetXmlRequest_DesktopOS_DesktopOSType_Type) Enum() *GetXmlRequest_DesktopOS_DesktopOSType_Type {
	p := new(GetXmlRequest_DesktopOS_DesktopOSType_Type)
	*p = x
	return p
}

func (x GetXmlRequest_DesktopOS_DesktopOSType_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetXmlRequest_DesktopOS_DesktopOSType_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_desktop_builder_proto_enumTypes[3].Descriptor()
}

func (GetXmlRequest_DesktopOS_DesktopOSType_Type) Type() protoreflect.EnumType {
	return &file_pkg_proto_desktop_builder_proto_enumTypes[3]
}

func (x GetXmlRequest_DesktopOS_DesktopOSType_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetXmlRequest_DesktopOS_DesktopOSType_Type.Descriptor instead.
func (GetXmlRequest_DesktopOS_DesktopOSType_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 0, 0, 2}
}

type GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType int32

const (
	GetXmlRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_TYPE_UNKNOWN  GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType = 0
	GetXmlRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_TYPE_KEYBOARD GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType = 1
)

// Enum value maps for GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType.
var (
	GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType_name = map[int32]string{
		0: "DESKTOP_DEVICE_INPUT_TYPE_UNKNOWN",
		1: "DESKTOP_DEVICE_INPUT_TYPE_KEYBOARD",
	}
	GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType_value = map[string]int32{
		"DESKTOP_DEVICE_INPUT_TYPE_UNKNOWN":  0,
		"DESKTOP_DEVICE_INPUT_TYPE_KEYBOARD": 1,
	}
)

func (x GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) Enum() *GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType {
	p := new(GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType)
	*p = x
	return p
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_desktop_builder_proto_enumTypes[4].Descriptor()
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) Type() protoreflect.EnumType {
	return &file_pkg_proto_desktop_builder_proto_enumTypes[4]
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType.Descriptor instead.
func (GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1, 0, 0}
}

type GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus int32

const (
	GetXmlRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_BUS_UNKNOWN GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus = 0
	GetXmlRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_BUS_PS2     GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus = 1
)

// Enum value maps for GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus.
var (
	GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus_name = map[int32]string{
		0: "DESKTOP_DEVICE_INPUT_BUS_UNKNOWN",
		1: "DESKTOP_DEVICE_INPUT_BUS_PS2",
	}
	GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus_value = map[string]int32{
		"DESKTOP_DEVICE_INPUT_BUS_UNKNOWN": 0,
		"DESKTOP_DEVICE_INPUT_BUS_PS2":     1,
	}
)

func (x GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) Enum() *GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus {
	p := new(GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus)
	*p = x
	return p
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_desktop_builder_proto_enumTypes[5].Descriptor()
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) Type() protoreflect.EnumType {
	return &file_pkg_proto_desktop_builder_proto_enumTypes[5]
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus.Descriptor instead.
func (GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1, 0, 1}
}

type GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType int32

const (
	GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DESKTOP_DEVICE_GRAPHIC_TYPE_UNKNOWN GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType = 0
	GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DESKTOP_DEVICE_GRAPHIC_TYPE_SPICE   GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType = 1
)

// Enum value maps for GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType.
var (
	GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType_name = map[int32]string{
		0: "DESKTOP_DEVICE_GRAPHIC_TYPE_UNKNOWN",
		1: "DESKTOP_DEVICE_GRAPHIC_TYPE_SPICE",
	}
	GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType_value = map[string]int32{
		"DESKTOP_DEVICE_GRAPHIC_TYPE_UNKNOWN": 0,
		"DESKTOP_DEVICE_GRAPHIC_TYPE_SPICE":   1,
	}
)

func (x GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType) Enum() *GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType {
	p := new(GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType)
	*p = x
	return p
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_desktop_builder_proto_enumTypes[6].Descriptor()
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType) Type() protoreflect.EnumType {
	return &file_pkg_proto_desktop_builder_proto_enumTypes[6]
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType.Descriptor instead.
func (GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1, 1, 0}
}

type GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType int32

const (
	GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DESKTOP_DEVICE_VIDEO_MODEL_TYPE_UNKNOWN GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType = 0
	GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DESKTOP_DEVICE_VIDEO_MODEL_TYPE_QXL     GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType = 1
)

// Enum value maps for GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType.
var (
	GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType_name = map[int32]string{
		0: "DESKTOP_DEVICE_VIDEO_MODEL_TYPE_UNKNOWN",
		1: "DESKTOP_DEVICE_VIDEO_MODEL_TYPE_QXL",
	}
	GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType_value = map[string]int32{
		"DESKTOP_DEVICE_VIDEO_MODEL_TYPE_UNKNOWN": 0,
		"DESKTOP_DEVICE_VIDEO_MODEL_TYPE_QXL":     1,
	}
)

func (x GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) Enum() *GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType {
	p := new(GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType)
	*p = x
	return p
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_desktop_builder_proto_enumTypes[7].Descriptor()
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) Type() protoreflect.EnumType {
	return &file_pkg_proto_desktop_builder_proto_enumTypes[7]
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType.Descriptor instead.
func (GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1, 2, 0, 0}
}

type GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType int32

const (
	GetXmlRequest_DesktopDevices_DesktopDeviceController_DESKTOP_DEVICE_CONTROLLER_TYPE_UNKNOWN GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType = 0
	GetXmlRequest_DesktopDevices_DesktopDeviceController_DESKTOP_DEVICE_CONTROLLER_TYPE_PCI     GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType = 1
	GetXmlRequest_DesktopDevices_DesktopDeviceController_DESKTOP_DEVICE_CONTROLLER_TYPE_PCIE    GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType = 2
)

// Enum value maps for GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType.
var (
	GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType_name = map[int32]string{
		0: "DESKTOP_DEVICE_CONTROLLER_TYPE_UNKNOWN",
		1: "DESKTOP_DEVICE_CONTROLLER_TYPE_PCI",
		2: "DESKTOP_DEVICE_CONTROLLER_TYPE_PCIE",
	}
	GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType_value = map[string]int32{
		"DESKTOP_DEVICE_CONTROLLER_TYPE_UNKNOWN": 0,
		"DESKTOP_DEVICE_CONTROLLER_TYPE_PCI":     1,
		"DESKTOP_DEVICE_CONTROLLER_TYPE_PCIE":    2,
	}
)

func (x GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType) Enum() *GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType {
	p := new(GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType)
	*p = x
	return p
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_desktop_builder_proto_enumTypes[8].Descriptor()
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType) Type() protoreflect.EnumType {
	return &file_pkg_proto_desktop_builder_proto_enumTypes[8]
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType.Descriptor instead.
func (GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1, 3, 0}
}

type GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel int32

const (
	GetXmlRequest_DesktopDevices_DesktopDeviceController_DESKTOP_DEVICE_CONTROLLER_MODEL_UNKNOWN   GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel = 0
	GetXmlRequest_DesktopDevices_DesktopDeviceController_DESKTOP_DEVICE_CONTROLLER_MODEL_PCIE_ROOT GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel = 1
)

// Enum value maps for GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel.
var (
	GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel_name = map[int32]string{
		0: "DESKTOP_DEVICE_CONTROLLER_MODEL_UNKNOWN",
		1: "DESKTOP_DEVICE_CONTROLLER_MODEL_PCIE_ROOT",
	}
	GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel_value = map[string]int32{
		"DESKTOP_DEVICE_CONTROLLER_MODEL_UNKNOWN":   0,
		"DESKTOP_DEVICE_CONTROLLER_MODEL_PCIE_ROOT": 1,
	}
)

func (x GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel) Enum() *GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel {
	p := new(GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel)
	*p = x
	return p
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_desktop_builder_proto_enumTypes[9].Descriptor()
}

func (GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel) Type() protoreflect.EnumType {
	return &file_pkg_proto_desktop_builder_proto_enumTypes[9]
}

func (x GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel.Descriptor instead.
func (GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1, 3, 1}
}

type GetXmlFromIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xml string `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetXmlFromIdRequest) Reset() {
	*x = GetXmlFromIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlFromIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlFromIdRequest) ProtoMessage() {}

func (x *GetXmlFromIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlFromIdRequest.ProtoReflect.Descriptor instead.
func (*GetXmlFromIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{0}
}

func (x *GetXmlFromIdRequest) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

func (x *GetXmlFromIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetXmlFromIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xml string `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
}

func (x *GetXmlFromIdResponse) Reset() {
	*x = GetXmlFromIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlFromIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlFromIdResponse) ProtoMessage() {}

func (x *GetXmlFromIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlFromIdResponse.ProtoReflect.Descriptor instead.
func (*GetXmlFromIdResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{1}
}

func (x *GetXmlFromIdResponse) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

type GetXmlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    GetXmlRequest_DesktopType     `protobuf:"varint,1,opt,name=type,proto3,enum=proto.GetXmlRequest_DesktopType" json:"type,omitempty"`
	Name    string                        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Os      *GetXmlRequest_DesktopOS      `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Devices *GetXmlRequest_DesktopDevices `protobuf:"bytes,4,opt,name=devices,proto3" json:"devices,omitempty"`
	Memory  *GetXmlRequest_DesktopMemory  `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Vcpu    *GetXmlRequest_DesktopVCPU    `protobuf:"bytes,6,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
}

func (x *GetXmlRequest) Reset() {
	*x = GetXmlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlRequest) ProtoMessage() {}

func (x *GetXmlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlRequest.ProtoReflect.Descriptor instead.
func (*GetXmlRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2}
}

func (x *GetXmlRequest) GetType() GetXmlRequest_DesktopType {
	if x != nil {
		return x.Type
	}
	return GetXmlRequest_DESKTOP_TYPE_UNKNOWN
}

func (x *GetXmlRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetXmlRequest) GetOs() *GetXmlRequest_DesktopOS {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *GetXmlRequest) GetDevices() *GetXmlRequest_DesktopDevices {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *GetXmlRequest) GetMemory() *GetXmlRequest_DesktopMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *GetXmlRequest) GetVcpu() *GetXmlRequest_DesktopVCPU {
	if x != nil {
		return x.Vcpu
	}
	return nil
}

type GetXmlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xml string `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
}

func (x *GetXmlResponse) Reset() {
	*x = GetXmlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlResponse) ProtoMessage() {}

func (x *GetXmlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlResponse.ProtoReflect.Descriptor instead.
func (*GetXmlResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{3}
}

func (x *GetXmlResponse) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

type GetViewerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xml string `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
}

func (x *GetViewerRequest) Reset() {
	*x = GetViewerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetViewerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewerRequest) ProtoMessage() {}

func (x *GetViewerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewerRequest.ProtoReflect.Descriptor instead.
func (*GetViewerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{4}
}

func (x *GetViewerRequest) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

type GetViewerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pwd          string `protobuf:"bytes,1,opt,name=pwd,proto3" json:"pwd,omitempty"`
	SpicePort    int32  `protobuf:"varint,2,opt,name=spice_port,json=spicePort,proto3" json:"spice_port,omitempty"`
	SpiceTlsPort int32  `protobuf:"varint,3,opt,name=spice_tls_port,json=spiceTlsPort,proto3" json:"spice_tls_port,omitempty"`
	VncPort      int32  `protobuf:"varint,4,opt,name=vnc_port,json=vncPort,proto3" json:"vnc_port,omitempty"`
	VncTlsPort   int32  `protobuf:"varint,5,opt,name=vnc_tls_port,json=vncTlsPort,proto3" json:"vnc_tls_port,omitempty"`
}

func (x *GetViewerResponse) Reset() {
	*x = GetViewerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetViewerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewerResponse) ProtoMessage() {}

func (x *GetViewerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewerResponse.ProtoReflect.Descriptor instead.
func (*GetViewerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{5}
}

func (x *GetViewerResponse) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *GetViewerResponse) GetSpicePort() int32 {
	if x != nil {
		return x.SpicePort
	}
	return 0
}

func (x *GetViewerResponse) GetSpiceTlsPort() int32 {
	if x != nil {
		return x.SpiceTlsPort
	}
	return 0
}

func (x *GetViewerResponse) GetVncPort() int32 {
	if x != nil {
		return x.VncPort
	}
	return 0
}

func (x *GetViewerResponse) GetVncTlsPort() int32 {
	if x != nil {
		return x.VncTlsPort
	}
	return 0
}

type GetXmlRequest_DesktopOS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *GetXmlRequest_DesktopOS_DesktopOSType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetXmlRequest_DesktopOS) Reset() {
	*x = GetXmlRequest_DesktopOS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlRequest_DesktopOS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlRequest_DesktopOS) ProtoMessage() {}

func (x *GetXmlRequest_DesktopOS) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlRequest_DesktopOS.ProtoReflect.Descriptor instead.
func (*GetXmlRequest_DesktopOS) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetXmlRequest_DesktopOS) GetType() *GetXmlRequest_DesktopOS_DesktopOSType {
	if x != nil {
		return x.Type
	}
	return nil
}

type GetXmlRequest_DesktopDevices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input      []*GetXmlRequest_DesktopDevices_DesktopDeviceInput      `protobuf:"bytes,1,rep,name=input,proto3" json:"input,omitempty"`
	Graphic    []*GetXmlRequest_DesktopDevices_DesktopDeviceGraphic    `protobuf:"bytes,2,rep,name=graphic,proto3" json:"graphic,omitempty"`
	Video      []*GetXmlRequest_DesktopDevices_DesktopDeviceVideo      `protobuf:"bytes,3,rep,name=video,proto3" json:"video,omitempty"`
	Controller []*GetXmlRequest_DesktopDevices_DesktopDeviceController `protobuf:"bytes,4,rep,name=controller,proto3" json:"controller,omitempty"`
}

func (x *GetXmlRequest_DesktopDevices) Reset() {
	*x = GetXmlRequest_DesktopDevices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlRequest_DesktopDevices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlRequest_DesktopDevices) ProtoMessage() {}

func (x *GetXmlRequest_DesktopDevices) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices.ProtoReflect.Descriptor instead.
func (*GetXmlRequest_DesktopDevices) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetXmlRequest_DesktopDevices) GetInput() []*GetXmlRequest_DesktopDevices_DesktopDeviceInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *GetXmlRequest_DesktopDevices) GetGraphic() []*GetXmlRequest_DesktopDevices_DesktopDeviceGraphic {
	if x != nil {
		return x.Graphic
	}
	return nil
}

func (x *GetXmlRequest_DesktopDevices) GetVideo() []*GetXmlRequest_DesktopDevices_DesktopDeviceVideo {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *GetXmlRequest_DesktopDevices) GetController() []*GetXmlRequest_DesktopDevices_DesktopDeviceController {
	if x != nil {
		return x.Controller
	}
	return nil
}

type GetXmlRequest_DesktopMemory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Unit  string `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *GetXmlRequest_DesktopMemory) Reset() {
	*x = GetXmlRequest_DesktopMemory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlRequest_DesktopMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlRequest_DesktopMemory) ProtoMessage() {}

func (x *GetXmlRequest_DesktopMemory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlRequest_DesktopMemory.ProtoReflect.Descriptor instead.
func (*GetXmlRequest_DesktopMemory) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 2}
}

func (x *GetXmlRequest_DesktopMemory) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetXmlRequest_DesktopMemory) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type GetXmlRequest_DesktopVCPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num       int32  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Placement string `protobuf:"bytes,2,opt,name=placement,proto3" json:"placement,omitempty"`
}

func (x *GetXmlRequest_DesktopVCPU) Reset() {
	*x = GetXmlRequest_DesktopVCPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlRequest_DesktopVCPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlRequest_DesktopVCPU) ProtoMessage() {}

func (x *GetXmlRequest_DesktopVCPU) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlRequest_DesktopVCPU.ProtoReflect.Descriptor instead.
func (*GetXmlRequest_DesktopVCPU) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 3}
}

func (x *GetXmlRequest_DesktopVCPU) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *GetXmlRequest_DesktopVCPU) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

type GetXmlRequest_DesktopOS_DesktopOSType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arch    GetXmlRequest_DesktopOS_DesktopOSType_Arch    `protobuf:"varint,1,opt,name=arch,proto3,enum=proto.GetXmlRequest_DesktopOS_DesktopOSType_Arch" json:"arch,omitempty"`
	Machine GetXmlRequest_DesktopOS_DesktopOSType_Machine `protobuf:"varint,2,opt,name=machine,proto3,enum=proto.GetXmlRequest_DesktopOS_DesktopOSType_Machine" json:"machine,omitempty"`
	Type    GetXmlRequest_DesktopOS_DesktopOSType_Type    `protobuf:"varint,3,opt,name=type,proto3,enum=proto.GetXmlRequest_DesktopOS_DesktopOSType_Type" json:"type,omitempty"`
}

func (x *GetXmlRequest_DesktopOS_DesktopOSType) Reset() {
	*x = GetXmlRequest_DesktopOS_DesktopOSType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlRequest_DesktopOS_DesktopOSType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlRequest_DesktopOS_DesktopOSType) ProtoMessage() {}

func (x *GetXmlRequest_DesktopOS_DesktopOSType) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlRequest_DesktopOS_DesktopOSType.ProtoReflect.Descriptor instead.
func (*GetXmlRequest_DesktopOS_DesktopOSType) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *GetXmlRequest_DesktopOS_DesktopOSType) GetArch() GetXmlRequest_DesktopOS_DesktopOSType_Arch {
	if x != nil {
		return x.Arch
	}
	return GetXmlRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_ARCH_UNKNOWN
}

func (x *GetXmlRequest_DesktopOS_DesktopOSType) GetMachine() GetXmlRequest_DesktopOS_DesktopOSType_Machine {
	if x != nil {
		return x.Machine
	}
	return GetXmlRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_MACHINE_UNKNOWN
}

func (x *GetXmlRequest_DesktopOS_DesktopOSType) GetType() GetXmlRequest_DesktopOS_DesktopOSType_Type {
	if x != nil {
		return x.Type
	}
	return GetXmlRequest_DesktopOS_DesktopOSType_DESKTOP_OS_TYPE_TYPE_UNKNOWN
}

type GetXmlRequest_DesktopDevices_DesktopDeviceInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType" json:"type,omitempty"`
	Bus  GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus  `protobuf:"varint,2,opt,name=bus,proto3,enum=proto.GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus" json:"bus,omitempty"`
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceInput) Reset() {
	*x = GetXmlRequest_DesktopDevices_DesktopDeviceInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlRequest_DesktopDevices_DesktopDeviceInput) ProtoMessage() {}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices_DesktopDeviceInput.ProtoReflect.Descriptor instead.
func (*GetXmlRequest_DesktopDevices_DesktopDeviceInput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1, 0}
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceInput) GetType() GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType {
	if x != nil {
		return x.Type
	}
	return GetXmlRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_TYPE_UNKNOWN
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceInput) GetBus() GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus {
	if x != nil {
		return x.Bus
	}
	return GetXmlRequest_DesktopDevices_DesktopDeviceInput_DESKTOP_DEVICE_INPUT_BUS_UNKNOWN
}

type GetXmlRequest_DesktopDevices_DesktopDeviceGraphic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType" json:"type,omitempty"`
	Listen string                                                                     `protobuf:"bytes,2,opt,name=listen,proto3" json:"listen,omitempty"`
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceGraphic) Reset() {
	*x = GetXmlRequest_DesktopDevices_DesktopDeviceGraphic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceGraphic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlRequest_DesktopDevices_DesktopDeviceGraphic) ProtoMessage() {}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceGraphic) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices_DesktopDeviceGraphic.ProtoReflect.Descriptor instead.
func (*GetXmlRequest_DesktopDevices_DesktopDeviceGraphic) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1, 1}
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceGraphic) GetType() GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType {
	if x != nil {
		return x.Type
	}
	return GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DESKTOP_DEVICE_GRAPHIC_TYPE_UNKNOWN
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceGraphic) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

type GetXmlRequest_DesktopDevices_DesktopDeviceVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceVideo) Reset() {
	*x = GetXmlRequest_DesktopDevices_DesktopDeviceVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlRequest_DesktopDevices_DesktopDeviceVideo) ProtoMessage() {}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceVideo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices_DesktopDeviceVideo.ProtoReflect.Descriptor instead.
func (*GetXmlRequest_DesktopDevices_DesktopDeviceVideo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1, 2}
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceVideo) GetModel() *GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type GetXmlRequest_DesktopDevices_DesktopDeviceController struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType  `protobuf:"varint,1,opt,name=type,proto3,enum=proto.GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType" json:"type,omitempty"`
	Index int32                                                                             `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Model GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel `protobuf:"varint,3,opt,name=model,proto3,enum=proto.GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel" json:"model,omitempty"`
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceController) Reset() {
	*x = GetXmlRequest_DesktopDevices_DesktopDeviceController{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlRequest_DesktopDevices_DesktopDeviceController) ProtoMessage() {}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceController) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices_DesktopDeviceController.ProtoReflect.Descriptor instead.
func (*GetXmlRequest_DesktopDevices_DesktopDeviceController) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1, 3}
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceController) GetType() GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType {
	if x != nil {
		return x.Type
	}
	return GetXmlRequest_DesktopDevices_DesktopDeviceController_DESKTOP_DEVICE_CONTROLLER_TYPE_UNKNOWN
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceController) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceController) GetModel() GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel {
	if x != nil {
		return x.Model
	}
	return GetXmlRequest_DesktopDevices_DesktopDeviceController_DESKTOP_DEVICE_CONTROLLER_MODEL_UNKNOWN
}

type GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType" json:"type,omitempty"`
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) Reset() {
	*x = GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_desktop_builder_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) ProtoMessage() {}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_desktop_builder_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel.ProtoReflect.Descriptor instead.
func (*GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) Descriptor() ([]byte, []int) {
	return file_pkg_proto_desktop_builder_proto_rawDescGZIP(), []int{2, 1, 2, 0}
}

func (x *GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel) GetType() GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType {
	if x != nil {
		return x.Type
	}
	return GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DESKTOP_DEVICE_VIDEO_MODEL_TYPE_UNKNOWN
}

var File_pkg_proto_desktop_builder_proto protoreflect.FileDescriptor

var file_pkg_proto_desktop_builder_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x58,
	0x6d, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x78, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x78, 0x6d,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x28, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x6d, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x78, 0x6d, 0x6c, 0x22, 0xf5, 0x17, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58,
	0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x4f, 0x53, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x3d, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x07, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x12, 0x34, 0x0a, 0x04, 0x76, 0x63, 0x70, 0x75, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x56, 0x43,
	0x50, 0x55, 0x52, 0x04, 0x76, 0x63, 0x70, 0x75, 0x1a, 0xc1, 0x04, 0x0a, 0x09, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x12, 0x40, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74,
	0x6f, 0x70, 0x4f, 0x53, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0xf1, 0x03, 0x0a, 0x0d, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x12, 0x45, 0x0a, 0x04, 0x61, 0x72,
	0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x52, 0x04, 0x61, 0x72, 0x63,
	0x68, 0x12, 0x4e, 0x0a, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x4f, 0x53, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65,
	0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x12, 0x45, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x2e,
	0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x49, 0x0a, 0x04, 0x41, 0x72, 0x63, 0x68,
	0x12, 0x20, 0x0a, 0x1c, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x4f, 0x53, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x4f, 0x53,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x58, 0x38, 0x36, 0x5f, 0x36,
	0x34, 0x10, 0x01, 0x22, 0x6f, 0x0a, 0x07, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x23,
	0x0a, 0x1f, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x4f, 0x53, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x4f,
	0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x5f, 0x50,
	0x43, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x4f,
	0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x5f, 0x51,
	0x33, 0x35, 0x10, 0x02, 0x22, 0x46, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x1c,
	0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x4f, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1c,
	0x0a, 0x18, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x4f, 0x53, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x48, 0x56, 0x4d, 0x10, 0x01, 0x1a, 0xbb, 0x0f, 0x0a,
	0x0e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12,
	0x4c, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x52, 0x0a,
	0x07, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69, 0x63, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x63, 0x52, 0x07, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69,
	0x63, 0x12, 0x4c, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x36, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x12,
	0x5b, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58,
	0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x1a, 0xa1, 0x03, 0x0a,
	0x12, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x61, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x4d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x5e, 0x0a, 0x03, 0x62, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x4c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58,
	0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x42, 0x75,
	0x73, 0x52, 0x03, 0x62, 0x75, 0x73, 0x22, 0x67, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x25, 0x0a, 0x21, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49,
	0x43, 0x45, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x26, 0x0a, 0x22, 0x44, 0x45, 0x53, 0x4b, 0x54,
	0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x4b, 0x45, 0x59, 0x42, 0x4f, 0x41, 0x52, 0x44, 0x10, 0x01, 0x22,
	0x5f, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x42, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x20, 0x44, 0x45, 0x53, 0x4b,
	0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54,
	0x5f, 0x42, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x20,
	0x0a, 0x1c, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45,
	0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x5f, 0x42, 0x55, 0x53, 0x5f, 0x50, 0x53, 0x32, 0x10, 0x01,
	0x1a, 0x81, 0x02, 0x0a, 0x14, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x63, 0x12, 0x65, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x51, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69,
	0x63, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x72, 0x61, 0x70, 0x68, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x22, 0x6a, 0x0a, 0x18, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x63,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x23, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f,
	0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x47, 0x52, 0x41, 0x50, 0x48, 0x49, 0x43, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x25, 0x0a,
	0x21, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f,
	0x47, 0x52, 0x41, 0x50, 0x48, 0x49, 0x43, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x50, 0x49,
	0x43, 0x45, 0x10, 0x01, 0x1a, 0x8b, 0x03, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x64, 0x0a, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x1a, 0x8e, 0x02, 0x0a, 0x17, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x7e, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x6a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x73, 0x0a,
	0x1b, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x27,
	0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x56,
	0x49, 0x44, 0x45, 0x4f, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x27, 0x0a, 0x23, 0x44, 0x45, 0x53,
	0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x56, 0x49, 0x44, 0x45,
	0x4f, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x51, 0x58, 0x4c,
	0x10, 0x01, 0x1a, 0xa5, 0x04, 0x0a, 0x17, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x6b,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x57, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x6e, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x58, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x22, 0x9a, 0x01, 0x0a, 0x1b, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x2a, 0x0a, 0x26, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56,
	0x49, 0x43, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x52, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x26, 0x0a,
	0x22, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f,
	0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x50, 0x43, 0x49, 0x10, 0x01, 0x12, 0x27, 0x0a, 0x23, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50,
	0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x4c,
	0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x43, 0x49, 0x45, 0x10, 0x02, 0x22, 0x7a,
	0x0a, 0x1c, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2b,
	0x0a, 0x27, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45,
	0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x52, 0x5f, 0x4d, 0x4f, 0x44, 0x45,
	0x4c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x2d, 0x0a, 0x29, 0x44,
	0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x43, 0x4f,
	0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x52, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x50,
	0x43, 0x49, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x54, 0x10, 0x01, 0x1a, 0x39, 0x0a, 0x0d, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x6e, 0x69, 0x74, 0x1a, 0x3d, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x56, 0x43, 0x50, 0x55, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a,
	0x10, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4b, 0x56,
	0x4d, 0x10, 0x01, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x78, 0x6d, 0x6c, 0x22, 0x24, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x56, 0x69,
	0x65, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x78,
	0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x78, 0x6d, 0x6c, 0x22, 0xa7, 0x01,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x70, 0x77, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x70, 0x69, 0x63, 0x65, 0x5f, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x69, 0x63, 0x65,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x70, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x6c,
	0x73, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x70,
	0x69, 0x63, 0x65, 0x54, 0x6c, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x6e,
	0x63, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x6e,
	0x63, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x76, 0x6e, 0x63, 0x5f, 0x74, 0x6c, 0x73,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x76, 0x6e, 0x63,
	0x54, 0x6c, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x32, 0xd6, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x58, 0x6d, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x58, 0x6d, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x12,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x58, 0x6d, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x73, 0x61, 0x72, 0x64, 0x2d, 0x76, 0x64, 0x69, 0x2f, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2f, 0x64,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_desktop_builder_proto_rawDescOnce sync.Once
	file_pkg_proto_desktop_builder_proto_rawDescData = file_pkg_proto_desktop_builder_proto_rawDesc
)

func file_pkg_proto_desktop_builder_proto_rawDescGZIP() []byte {
	file_pkg_proto_desktop_builder_proto_rawDescOnce.Do(func() {
		file_pkg_proto_desktop_builder_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_desktop_builder_proto_rawDescData)
	})
	return file_pkg_proto_desktop_builder_proto_rawDescData
}

var file_pkg_proto_desktop_builder_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_pkg_proto_desktop_builder_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_proto_desktop_builder_proto_goTypes = []interface{}{
	(GetXmlRequest_DesktopType)(0),                                                                           // 0: proto.GetXmlRequest.DesktopType
	(GetXmlRequest_DesktopOS_DesktopOSType_Arch)(0),                                                          // 1: proto.GetXmlRequest.DesktopOS.DesktopOSType.Arch
	(GetXmlRequest_DesktopOS_DesktopOSType_Machine)(0),                                                       // 2: proto.GetXmlRequest.DesktopOS.DesktopOSType.Machine
	(GetXmlRequest_DesktopOS_DesktopOSType_Type)(0),                                                          // 3: proto.GetXmlRequest.DesktopOS.DesktopOSType.Type
	(GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputType)(0),                              // 4: proto.GetXmlRequest.DesktopDevices.DesktopDeviceInput.DesktopDeviceInputType
	(GetXmlRequest_DesktopDevices_DesktopDeviceInput_DesktopDeviceInputBus)(0),                               // 5: proto.GetXmlRequest.DesktopDevices.DesktopDeviceInput.DesktopDeviceInputBus
	(GetXmlRequest_DesktopDevices_DesktopDeviceGraphic_DesktopDeviceGraphicType)(0),                          // 6: proto.GetXmlRequest.DesktopDevices.DesktopDeviceGraphic.DesktopDeviceGraphicType
	(GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel_DesktopDeviceVideoModelType)(0), // 7: proto.GetXmlRequest.DesktopDevices.DesktopDeviceVideo.DesktopDeviceVideoModel.DesktopDeviceVideoModelType
	(GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerType)(0),                    // 8: proto.GetXmlRequest.DesktopDevices.DesktopDeviceController.DesktopDeviceControllerType
	(GetXmlRequest_DesktopDevices_DesktopDeviceController_DesktopDeviceControllerModel)(0),                   // 9: proto.GetXmlRequest.DesktopDevices.DesktopDeviceController.DesktopDeviceControllerModel
	(*GetXmlFromIdRequest)(nil),                                                                              // 10: proto.GetXmlFromIdRequest
	(*GetXmlFromIdResponse)(nil),                                                                             // 11: proto.GetXmlFromIdResponse
	(*GetXmlRequest)(nil),                                                                                    // 12: proto.GetXmlRequest
	(*GetXmlResponse)(nil),                                                                                   // 13: proto.GetXmlResponse
	(*GetViewerRequest)(nil),                                                                                 // 14: proto.GetViewerRequest
	(*GetViewerResponse)(nil),                                                                                // 15: proto.GetViewerResponse
	(*GetXmlRequest_DesktopOS)(nil),                                                                          // 16: proto.GetXmlRequest.DesktopOS
	(*GetXmlRequest_DesktopDevices)(nil),                                                                     // 17: proto.GetXmlRequest.DesktopDevices
	(*GetXmlRequest_DesktopMemory)(nil),                                                                      // 18: proto.GetXmlRequest.DesktopMemory
	(*GetXmlRequest_DesktopVCPU)(nil),                                                                        // 19: proto.GetXmlRequest.DesktopVCPU
	(*GetXmlRequest_DesktopOS_DesktopOSType)(nil),                                                            // 20: proto.GetXmlRequest.DesktopOS.DesktopOSType
	(*GetXmlRequest_DesktopDevices_DesktopDeviceInput)(nil),                                                  // 21: proto.GetXmlRequest.DesktopDevices.DesktopDeviceInput
	(*GetXmlRequest_DesktopDevices_DesktopDeviceGraphic)(nil),                                                // 22: proto.GetXmlRequest.DesktopDevices.DesktopDeviceGraphic
	(*GetXmlRequest_DesktopDevices_DesktopDeviceVideo)(nil),                                                  // 23: proto.GetXmlRequest.DesktopDevices.DesktopDeviceVideo
	(*GetXmlRequest_DesktopDevices_DesktopDeviceController)(nil),                                             // 24: proto.GetXmlRequest.DesktopDevices.DesktopDeviceController
	(*GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel)(nil),                          // 25: proto.GetXmlRequest.DesktopDevices.DesktopDeviceVideo.DesktopDeviceVideoModel
}
var file_pkg_proto_desktop_builder_proto_depIdxs = []int32{
	0,  // 0: proto.GetXmlRequest.type:type_name -> proto.GetXmlRequest.DesktopType
	16, // 1: proto.GetXmlRequest.os:type_name -> proto.GetXmlRequest.DesktopOS
	17, // 2: proto.GetXmlRequest.devices:type_name -> proto.GetXmlRequest.DesktopDevices
	18, // 3: proto.GetXmlRequest.memory:type_name -> proto.GetXmlRequest.DesktopMemory
	19, // 4: proto.GetXmlRequest.vcpu:type_name -> proto.GetXmlRequest.DesktopVCPU
	20, // 5: proto.GetXmlRequest.DesktopOS.type:type_name -> proto.GetXmlRequest.DesktopOS.DesktopOSType
	21, // 6: proto.GetXmlRequest.DesktopDevices.input:type_name -> proto.GetXmlRequest.DesktopDevices.DesktopDeviceInput
	22, // 7: proto.GetXmlRequest.DesktopDevices.graphic:type_name -> proto.GetXmlRequest.DesktopDevices.DesktopDeviceGraphic
	23, // 8: proto.GetXmlRequest.DesktopDevices.video:type_name -> proto.GetXmlRequest.DesktopDevices.DesktopDeviceVideo
	24, // 9: proto.GetXmlRequest.DesktopDevices.controller:type_name -> proto.GetXmlRequest.DesktopDevices.DesktopDeviceController
	1,  // 10: proto.GetXmlRequest.DesktopOS.DesktopOSType.arch:type_name -> proto.GetXmlRequest.DesktopOS.DesktopOSType.Arch
	2,  // 11: proto.GetXmlRequest.DesktopOS.DesktopOSType.machine:type_name -> proto.GetXmlRequest.DesktopOS.DesktopOSType.Machine
	3,  // 12: proto.GetXmlRequest.DesktopOS.DesktopOSType.type:type_name -> proto.GetXmlRequest.DesktopOS.DesktopOSType.Type
	4,  // 13: proto.GetXmlRequest.DesktopDevices.DesktopDeviceInput.type:type_name -> proto.GetXmlRequest.DesktopDevices.DesktopDeviceInput.DesktopDeviceInputType
	5,  // 14: proto.GetXmlRequest.DesktopDevices.DesktopDeviceInput.bus:type_name -> proto.GetXmlRequest.DesktopDevices.DesktopDeviceInput.DesktopDeviceInputBus
	6,  // 15: proto.GetXmlRequest.DesktopDevices.DesktopDeviceGraphic.type:type_name -> proto.GetXmlRequest.DesktopDevices.DesktopDeviceGraphic.DesktopDeviceGraphicType
	25, // 16: proto.GetXmlRequest.DesktopDevices.DesktopDeviceVideo.model:type_name -> proto.GetXmlRequest.DesktopDevices.DesktopDeviceVideo.DesktopDeviceVideoModel
	8,  // 17: proto.GetXmlRequest.DesktopDevices.DesktopDeviceController.type:type_name -> proto.GetXmlRequest.DesktopDevices.DesktopDeviceController.DesktopDeviceControllerType
	9,  // 18: proto.GetXmlRequest.DesktopDevices.DesktopDeviceController.model:type_name -> proto.GetXmlRequest.DesktopDevices.DesktopDeviceController.DesktopDeviceControllerModel
	7,  // 19: proto.GetXmlRequest.DesktopDevices.DesktopDeviceVideo.DesktopDeviceVideoModel.type:type_name -> proto.GetXmlRequest.DesktopDevices.DesktopDeviceVideo.DesktopDeviceVideoModel.DesktopDeviceVideoModelType
	10, // 20: proto.DesktopBuilder.GetXmlFromId:input_type -> proto.GetXmlFromIdRequest
	12, // 21: proto.DesktopBuilder.GetXml:input_type -> proto.GetXmlRequest
	14, // 22: proto.DesktopBuilder.GetViewer:input_type -> proto.GetViewerRequest
	11, // 23: proto.DesktopBuilder.GetXmlFromId:output_type -> proto.GetXmlFromIdResponse
	13, // 24: proto.DesktopBuilder.GetXml:output_type -> proto.GetXmlResponse
	15, // 25: proto.DesktopBuilder.GetViewer:output_type -> proto.GetViewerResponse
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pkg_proto_desktop_builder_proto_init() }
func file_pkg_proto_desktop_builder_proto_init() {
	if File_pkg_proto_desktop_builder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_desktop_builder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlFromIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlFromIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetViewerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetViewerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlRequest_DesktopOS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlRequest_DesktopDevices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlRequest_DesktopMemory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlRequest_DesktopVCPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlRequest_DesktopOS_DesktopOSType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlRequest_DesktopDevices_DesktopDeviceInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlRequest_DesktopDevices_DesktopDeviceGraphic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlRequest_DesktopDevices_DesktopDeviceVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlRequest_DesktopDevices_DesktopDeviceController); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_desktop_builder_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXmlRequest_DesktopDevices_DesktopDeviceVideo_DesktopDeviceVideoModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_desktop_builder_proto_rawDesc,
			NumEnums:      10,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_desktop_builder_proto_goTypes,
		DependencyIndexes: file_pkg_proto_desktop_builder_proto_depIdxs,
		EnumInfos:         file_pkg_proto_desktop_builder_proto_enumTypes,
		MessageInfos:      file_pkg_proto_desktop_builder_proto_msgTypes,
	}.Build()
	File_pkg_proto_desktop_builder_proto = out.File
	file_pkg_proto_desktop_builder_proto_rawDesc = nil
	file_pkg_proto_desktop_builder_proto_goTypes = nil
	file_pkg_proto_desktop_builder_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DesktopBuilderClient is the client API for DesktopBuilder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DesktopBuilderClient interface {
	GetXmlFromId(ctx context.Context, in *GetXmlFromIdRequest, opts ...grpc.CallOption) (*GetXmlFromIdResponse, error)
	GetXml(ctx context.Context, in *GetXmlRequest, opts ...grpc.CallOption) (*GetXmlResponse, error)
	GetViewer(ctx context.Context, in *GetViewerRequest, opts ...grpc.CallOption) (*GetViewerResponse, error)
}

type desktopBuilderClient struct {
	cc grpc.ClientConnInterface
}

func NewDesktopBuilderClient(cc grpc.ClientConnInterface) DesktopBuilderClient {
	return &desktopBuilderClient{cc}
}

func (c *desktopBuilderClient) GetXmlFromId(ctx context.Context, in *GetXmlFromIdRequest, opts ...grpc.CallOption) (*GetXmlFromIdResponse, error) {
	out := new(GetXmlFromIdResponse)
	err := c.cc.Invoke(ctx, "/proto.DesktopBuilder/GetXmlFromId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopBuilderClient) GetXml(ctx context.Context, in *GetXmlRequest, opts ...grpc.CallOption) (*GetXmlResponse, error) {
	out := new(GetXmlResponse)
	err := c.cc.Invoke(ctx, "/proto.DesktopBuilder/GetXml", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopBuilderClient) GetViewer(ctx context.Context, in *GetViewerRequest, opts ...grpc.CallOption) (*GetViewerResponse, error) {
	out := new(GetViewerResponse)
	err := c.cc.Invoke(ctx, "/proto.DesktopBuilder/GetViewer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DesktopBuilderServer is the server API for DesktopBuilder service.
type DesktopBuilderServer interface {
	GetXmlFromId(context.Context, *GetXmlFromIdRequest) (*GetXmlFromIdResponse, error)
	GetXml(context.Context, *GetXmlRequest) (*GetXmlResponse, error)
	GetViewer(context.Context, *GetViewerRequest) (*GetViewerResponse, error)
}

// UnimplementedDesktopBuilderServer can be embedded to have forward compatible implementations.
type UnimplementedDesktopBuilderServer struct {
}

func (*UnimplementedDesktopBuilderServer) GetXmlFromId(context.Context, *GetXmlFromIdRequest) (*GetXmlFromIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetXmlFromId not implemented")
}
func (*UnimplementedDesktopBuilderServer) GetXml(context.Context, *GetXmlRequest) (*GetXmlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetXml not implemented")
}
func (*UnimplementedDesktopBuilderServer) GetViewer(context.Context, *GetViewerRequest) (*GetViewerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetViewer not implemented")
}

func RegisterDesktopBuilderServer(s *grpc.Server, srv DesktopBuilderServer) {
	s.RegisterService(&_DesktopBuilder_serviceDesc, srv)
}

func _DesktopBuilder_GetXmlFromId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetXmlFromIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopBuilderServer).GetXmlFromId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DesktopBuilder/GetXmlFromId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopBuilderServer).GetXmlFromId(ctx, req.(*GetXmlFromIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopBuilder_GetXml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetXmlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopBuilderServer).GetXml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DesktopBuilder/GetXml",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopBuilderServer).GetXml(ctx, req.(*GetXmlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopBuilder_GetViewer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopBuilderServer).GetViewer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DesktopBuilder/GetViewer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopBuilderServer).GetViewer(ctx, req.(*GetViewerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DesktopBuilder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DesktopBuilder",
	HandlerType: (*DesktopBuilderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetXmlFromId",
			Handler:    _DesktopBuilder_GetXmlFromId_Handler,
		},
		{
			MethodName: "GetXml",
			Handler:    _DesktopBuilder_GetXml_Handler,
		},
		{
			MethodName: "GetViewer",
			Handler:    _DesktopBuilder_GetViewer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/desktop-builder.proto",
}
