[project]
name = "isardvdi-backupninja"
version = "0.0.0"
requires-python = ">=3.14,<3.15"
dependencies = [
  "isardvdi-apiv4-client",
  "isardvdi-common",
  "pyjwt==2.13.0",
  "requests==2.34.2",
  "rethinkdb @ https://github.com/isard-vdi/rethinkdb-python/archive/de0aa01a894bc08c3d8ecb9333bec2eafe9fd504.tar.gz",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
bypass-selection = true

[tool.isardvdi.system-deps]
apk-build = ["build-base", "libffi-dev", "libjpeg-turbo-dev", "musl-dev", "openssl-dev", "zlib-dev"]
apk-runtime = ["bash", "borgbackup", "coreutils", "curl", "envsubst", "flock", "jq", "libffi", "libjpeg-turbo", "nfs-utils", "openssl", "redis", "zlib"]
