enabled:
  type: boolean
  required: true
migration:
  type: dict
  schema:
    notification_bar:
      type: dict
      schema:
        level:
          required: false
          type: string
          coerce: sanitize
        template:
          required: false
          type: string
          coerce: sanitize
        enabled:
          required: false
          type: boolean
    allow_automigration:
      required: false
      type: boolean
    export:
      required: false
      type: boolean
    import:
      required: false
      type: boolean
    action_after_migrate:
      required: false
      type: string
      coerce: sanitize
    force_migration:
      required: false
      type: boolean
ldap_config:
  type: dict
  schema: ldap_config
saml_config:
  type: dict
  schema: saml_config
google_config:
  type: dict
  schema: google_config
